var flowLogic	= {
		'flow_202001'		: {
			'flow_nm'	: '예약이체',
			'flow_data'	: [
	    	   {'id':'API_TrnSctrResv0300'		,'name':'예약이체 등록 / 자주쓰는 계좌 등록'	,'explain':'예약이체 등록 신규(자주쓰는 계좌도 동시 등록 가능'},
	    	   {'id':'API_TrnSctrRevo0300'		,'name':'예약이체 등록취소'	                    ,'explain':'예약이체 등록취소'},
	    	   {'id':'API_TrnMulpMutr0100'		,'name':'예약이체등록 및 이체처리결과조회'	    ,'explain':'예약이체처리결과조회(총건/대량)'},
	    	   {'id':'API_TrnDetrList0300_01'	,'name':'자주쓰는계좌 등록'						,'explain':'자주쓰는계좌 등록'},
	    	   {'id':'API_TrnImtrRigt0101_02'	,'name':'최근입금_자주쓰는계좌조회'				,'explain':'최근입금 및 자주쓰는계좌 조회'},
	    	]
		},
		'flow_00'		: {
			'flow_nm'	: '테스트',
			'flow_data'	: [
	    	   {'id':'API_PhotoTest'			,'name':'고객정보 이미지 테스트'				,'explain':'테스트 API : 삭제 예정!!!'},
	    	   {'id':'API_DepDeauRegi0200_01'	,'name':'단순수취인조회'						,'explain':'입력된 계좌가 실제로 존재 하는지 여부만 확인'},
	    	   {'id':'API_NomAcco0700_04'		,'name':'비대면 실명확인조회'					,'explain':'[완료] 비대면 실명확인조회 : 주민번호 일치여부까지 확인'},
	    	   {'id':'API_ComScra0100'			,'name':'스크래핑사전데이타조회(휴일여부조회)'	,'explain':'[완료] 스크래핑사전데이타조회(휴일여부조회)'},
	    	   {'id':'API_SeuDvdeJoin0200_02'	,'name':'PC지정서비스등록 '						,'explain':'고객PC지정단말기등록'},
	    	   {'id':'API_SeuDvdeJoin0200_01'	,'name':'PC지정서비스가입여부조회'				,'explain':'본 서비스 가입여부에 따라 추가인증 과정 수행여부 결정'},
	    	   {'id':'API_CerIssu0200_02'		,'name':'공인인증서 PC지정여부 확인'			,'explain':'[로그정보없음] 공인인증서 PC지정여부 확인'},
	    	   {'id':'API_comCert0100_07'		,'name':'공인인증서서명검증'					,'explain':'공인인증서 검증시 인증서 조회'},
	    	   {'id':'API_CerIssu0210'			,'name':'공인인증서조회'						,'explain':'당행 발급 공인인증서 조회'},
	    	   {'id':'API_comCert0100_02'		,'name':'공인인증서정보조회'					,'explain':'발급 및 등록된 공인인증서 정보 조회'},
	    	   {'id':'API_CerIssu0200_01'		,'name':'공인인증서본인확인'					,'explain':'공인인증서를 통한 본인확인'},
	    	   {'id':'API_CerIssu0200'			,'name':'공인인증서 등록'						,'explain':''},
			   {'id':'API_DepDech0200'			,'name':'적금 납입일 변경 선조회'				,'explain':'[완료] 적금 납입일 변경 선조회 (TRTM_DVCD:0조회,:1변경 '},
               {'id':'API_DepDech0100'			,'name':'적금 납입일변경 가능 계좌 조회'		,'explain':'[완료] 적금 납입일변경 가능 계좌 조회'},
	    	]
		},
	'flow_01'		: {
		'flow_nm'	: '로그인 프로세스',
		'flow_data'	: [
    	   {'id':'API_LogLogn0100_01'	,'name':'ID/PW 로그인' 						,'explain':'테스트 API : 삭제 예정!!!'},
    	   {'id':'API_LogLogn0100_02'	,'name':'공인증서 로그인' 					,'explain':'전자금융 가입고객 공인인증서를 이용한 로그인'},
    	   {'id':'API_LogLogn0100_03'	,'name':'로그인공통처리' 					,'explain':'사용자 세션에 저장할 전자금융정보 조회'},
    	   {'id':'API_LogLogn0100_04'	,'name':'로그인세션 TTL연장/최초로그인체크' ,'explain':'로그인 세션시간을 10분으로 초기화'},
    	   {'id':'API_ComLgcd0101_01'	,'name':'로그인시약관동의' 					,'explain':'약관동의 처리 후 임시세션 삭제'},
    	   {'id':'API_LogLogn0200_01'	,'name':'로그아웃' 							,'explain':'사용자 로그인 세션 삭제'},
    	   {'id':'API_ComFdsUtil'		,'name':'FDS연계' 							,'explain':'이상금융거래탐지 위한 로그인 단말정보 수집/탐지'}
    	]
	}
	,'flow_02'		: {
		'flow_nm'	: '인증 프로세스',
		'flow_data'	: [
    	   {'id':'API_PA_TokenIssue'	,'name':'사설인증토큰발급'		,'explain':'중앙회 사설인증 서비스, 인증토큰 발급'},
    	   {'id':'API_PA_TxCreate'		,'name':'사설인증랜덤발급요청'	,'explain':'중앙회 사설인증 서비스, 일회용 검증키 발급'},
    	   {'id':'API_PA_TxSign'		,'name':'사설인증서명검증'		,'explain':'중앙회 사설인증 서비스, 사설인증 서명 검증'},
    	   {'id':'API_comCert0100_02'	,'name':'공인인증서정보조회'	,'explain':'발급 및 등록된 공인인증서 정보 조회'},
    	   {'id':'API_comCert0100_07'	,'name':'공인인증서서명검증'	,'explain':'당행 공인인증서가 생성한 서명 검증'},
    	   {'id':'API_CerIssu0210'		,'name':'공인인증서조회'		,'explain':'등록된 공인인증서 조회'},
    	   {'id':'API_SeuOotp0200_01'	,'name':'OTP온라인타기관등록'	,'explain':'공인인증서 발급/재발급, 검증, 갱신, 폐기, 타기관등록/해지 처리 위한 인증서 등록'},
    	   {'id':'API_CerIssu0200_01'	,'name':'공인인증서본인확인'	,'explain':'공인인증서를 통한 본인확인'},
    	   {'id':'API_CerIssu0200'		,'name':'공인인증서 등록'		,'explain':''}
		]
	}
	,'flow_03'		: {
		'flow_nm'	: 'OTP 프로세스',
		'flow_data'	: [
			{'id':'API_comSecu0200_02' 	,'name':'OTP인증요청'  					,'explain':'OTP 인증 요청'},
			{'id':'API_SeuOtprOtps0100' ,'name':'OTP보정요청'  					,'explain':'OTP 보정 요청'},
			{'id':'API_IbaDrcl0200_01'	,'name':'고객OTP정보조회'  				,'explain':'고객에게 발급된 OTP 정보 조회'},
			{'id':'API_SeuOotp0100_02'	,'name':'고객별OTP원장조회'  				,'explain':''},
			{'id':'API_SeuOotp0100_03'	,'name':'OTP기기별이용등록기관내역조회'		,'explain':''},
			{'id':'API_comSecu0200_03'	,'name':'OTP거래인증'						,'explain':'OTP거래인증'},
			{'id':'API_comSecu0200_01'	,'name':'OTP일회용PIN요청/응답'			,'explain':'OTP인증'},
			{'id':'API_comSecu0200_04'	,'name':'OTP거래정보전송'					,'explain':'OTP거래정보전송'},
			{'id':'API_comSecu0200_05'	,'name':'OTP기기상세조회'					,'explain':'OTP기기상세조회'},
			{'id':'API_SeuMotpSett0100'	,'name':'mOTP관리'						,'explain':'mOTP 사용 발급'}
		]
	}
	,'flow_04'		: {
		'flow_nm'	: '고객정보 프로세스',
		'flow_data'	: [
			{'id':'API_LogIdfn0100_01'		,'name':'사용자ID조회'					,'explain':'전자금융 사용자 ID 조회'},
			{'id':'API_CusIqmo0200'			,'name':'고객정보조회'					,'explain':'전자금융ID를 이용하여 상세 고객정보를 조회'},
			{'id':'API_CusIqmo0300'			,'name':'고객정보변경'					,'explain':'고객정보변경(개인/법인)'},
			{'id':'API_LogFupw0100_01'		,'name':'최초 비밀번호 등록'				,'explain':'전자금융 사용자 등록 이후 최초 비밀번호 등록 과정'},
			{'id':'API_CusPwmo0200'			,'name':'비밀번호 변경'					,'explain':'전자금융 사용자 비밀번호 변경'},
			{'id':'API_LogUrpw0200_01'		,'name':'비밀번호분실재등록'				,'explain':'전자금융 사용자 비밀번호 분실 후 재등록'},
			{'id':'API_LogUrpw0100_01'		,'name':'비밀번호분실재등록 선조회'			,'explain':''},
			{'id':'API_SeuAdsvJoin0200_01'	,'name':'추가인증서비스가입 '				,'explain':'추가인증서비스가입'},
			{'id':'API_SeuDvdeJoin0200_01'	,'name':'PC지정서비스가입여부조회'			,'explain':'본 서비스 가입여부에 따라 추가인증 과정 수행여부 결정'},
			{'id':'API_SeuDvdeJoin0200_02'	,'name':'PC지정서비스등록 '				,'explain':'고객PC지정단말기등록'},
			{'id':'API_SeuDvdeJoin0200_03'	,'name':'PC지정서비스변경 또는 삭제(해지) '	,'explain':'고객PC지정단말기변경/삭제 (TMNL_ID는 등록시 입력된 번호)'},
			{'id':'API_CusIqmo0200_01'		,'name':'전자금융사기예방서비스가입내역조회'	,'explain':'전자금융사기예방서비스에 가입된 추가인증종류 조회'},
			{'id':'API_LogUrpwPhon0200'		,'name':'ARS인증용전화번호조회'			,'explain':'사용자비밀번호재등록 등 ARS인증을 위한 고객원장 등록 전화번호 조회'},
			{'id':'API_IbaApwl0100'			,'name':'계좌비밀번호3회오류계좌목록조회'	,'explain':''},
			{'id':'API_IbaApwl0200'			,'name':'계좌비밀번호3회오류해제'			,'explain':''},
			{'id':'API_IbaAcpw0300'			,'name':'계좌비밀번호변경'					,'explain':''}
		]
	}
	,'flow_05'		: {
		'flow_nm'	: '조회 프로세스',
		'flow_data'	: [
			{'id':'API_InqOvvi0100_01'	,'name':'전계좌조회'		,'explain':'당행 전체계좌 조회'},
			{'id':'API_InqOvvi0200'		,'name':'계좌상세조회'	,'explain':'계좌 상세내역 조회'},
			{'id':'API_InqTrhi0100_01'	,'name':'거래내역조회'	,'explain':'거래내역 조회'}
		]
	}
	,'flow_06'		: {
		'flow_nm'	: '이체 프로세스',
		'flow_data'	: [
		    {'id':'API_ComFdsUtil'		,'name':'FDS연계' 							,'explain':'이상금융거래탐지 위한 로그인 단말정보 수집/탐지'},
			{'id':'API_TrnImtrRigt0101_01'		,'name':'이체가능금액조회'							,'explain':'일/회 단위의 이체 가능금액 조회'},
			{'id':'API_TrnImtrRigt0100_01'		,'name':'수취조회'								,'explain':'수취인 성명 및 수취계좌번호 조회(당행)'},
			{'id':'API_TrnImtrRigt0100_02'		,'name':'수취조회'								,'explain':'수취인 성명 및 수취계좌번호 조회(타행)'},
			{'id':'API_TrnImtrRigt0100_03'		,'name':'수취조회'								,'explain':'수취인 성명 및 수취계좌번호 조회(미통합)'},
			{'id':'API_TrnImtrRigt0200_01'		,'name':'즉시이체_자주쓰는계좌등록'					,'explain':'즉시이체 및 자주쓰는계좌 등록(당행)'},
			{'id':'API_TrnImtrRigt0200_01_02'	,'name':'즉시이체_자주쓰는계좌등록'					,'explain':'즉시이체 및 자주쓰는계좌 등록(타행)'},
			{'id':'API_TrnImtrRigt0200_01_03'	,'name':'즉시이체_자주쓰는계좌등록'					,'explain':'즉시이체 및 자주쓰는계좌 등록(미통합)'},
			{'id':'API_TrnImtrRigt0101_02'		,'name':'최근입금_자주쓰는계좌조회'					,'explain':'최근입금 및 자주쓰는계좌 조회'},
			{'id':'API_IbaTlrd0100'				,'name':'이체한도감액신청'							,'explain':'이체한도 감액 신청'},
			{'id':'API_IbaTlrdUpto0100'			,'name':'이체한도증액신청'							,'explain':'이체한도 증액 신청'},
			{'id':'API_DepDeauRegi0200_01'		,'name':'단순수취인조회'					,'explain':''},
			{'id':'API_TrnAutrAuto0100_01'		,'name':'자동이체(타행)수취인조회'					,'explain':''},
			{'id':'API_TrnAutrAuto0400'			,'name':'자동이체(당행)등록'						,'explain':''},
			{'id':'API_TrnAutrAuto0400_01'		,'name':'자동이체(타행)등록'						,'explain':''},
			{'id':'API_TrnAutrRevo0100_01'		,'name':'자동이체(당타행)등록내역조회'				,'explain':''},
			{'id':'API_TrnAutrRevo0500'			,'name':'자동이체(당타행)변경등록'					,'explain':''},
			{'id':'API_TrnAutrRevo0700'			,'name':'자동이체(당타행)해지등록'					,'explain':''},
			{'id':'API_TrnAutrTran0100_01'		,'name':'자동이체(당타행)이체결과조회'				,'explain':''},
			{'id':'API_TrnAucmAuto0500'			,'name':'자동이체(CMS)타행출금관리'				,'explain':'자동이체(CMS)타행출금 등록 및 변경, 해지'},
			{'id':'API_comCert0100_04'			,'name':'자동이체(CMS)타행출금동의자료등록'			,'explain':'사용안함.(API_comCert0100_03 합처짐)'},
			{'id':'API_TrnAucmAuto0800'			,'name':'자동이체(CMS)저축은행출금등록'				,'explain':'자동이체(CMS) 저축은행출금 등록'},
			{'id':'API_TrnAucmRevo0100_01'		,'name':'자동이체(CMS)등록내역조회'				,'explain':''},
			{'id':'API_TrnAucmTran0100_01'		,'name':'자동이체(CMS)이체결과조회'				,'explain':''},
			{'id':'API_TrnImtrRigt0100'			,'name':'지연이체서비스 조회'						,'explain':'지연이체 서비스 등록 전 정보조회'},
			{'id':'API_TrnImtrRigt0106'			,'name':'장애은행조회'							,'explain':'장애은행 조회'},
			{'id':'API_TrnImtrRigt0107'			,'name':'입금지정계좌조회/입금지정계좌보유여부조회'	,'explain':'입금지정계좌 목록 조회'},
			{'id':'API_TrnDetrList0100_01'		,'name':'지연이체서비스가입여부조회'				,'explain':'즉시이체 거래 시, 지연이체서비스 가입자는 지연이체 화면 이동'},
			{'id':'API_IbaDtrn0200'				,'name':'지연이체서비스관리'						,'explain':'지연이체 서비스 등록 및 변경'},
			{'id':'API_IbaDeptJore0200'			,'name':'입금지정계좌관리'							,'explain':'입금지정계좌 등록 및 해지'}
		]
	}
	,'flow_07'		: {
		'flow_nm'	: '스마트출금 프로세스',
		'flow_data'	: [
			{'id':'API_TrnSmatAcmo0100'		,'name':'스마트ATM 출금 계좌변경 전조회'		,'explain':''},
			{'id':'API_TrnSmatAcmo0200'		,'name':'스마트ATM 출금 계좌변경 완료'		,'explain':''},
			{'id':'API_TrnSmatAtsr0100'		,'name':'가까운ATM 찾기'					,'explain':''},
			{'id':'API_TrnSmatAtsr0200_01'	,'name':'지역별ATM_광역/시/도 선택'		,'explain':''},
			{'id':'API_TrnSmatSmwt0100_01'	,'name':'스마트ATM 출금 확인/취소'			,'explain':''},
			{'id':'API_TrnSmatSmwt0100_02'	,'name':'스마트ATM 출금 재신청'			,'explain':''},
			{'id':'API_TrnSmatSmwt0100'		,'name':'스마트ATM 출금 정보 입력'			,'explain':''},
			{'id':'API_TrnSmatSmwt0101'		,'name':'스마트ATM 출금 인증 번호 요청'		,'explain':''},
			{'id':'API_TrnSmatSmwt0200'		,'name':'스마트ATM 출금 완료'				,'explain':''},
			{'id':'API_TrnSmatSvad0100'		,'name':'스마트ATM 출금 서비스 등록'		,'explain':''},
			{'id':'API_TrnSmatSvad0200'		,'name':'스마트ATM 출금 서비스 등록 완료'	,'explain':''},
			{'id':'API_TrnSmatSmwt0100_03'	,'name':'ATM스마트 출금 서비스 해지'			,'explain':''}
		]
	}
	,'flow_08'		: {
		'flow_nm'	: '예적금 프로세스',
		'flow_data'	: [
			{'id':'API_DepDeindLst0400_01'	,'name':'정기예금, 적금 신청 전조회'		,'explain':'예적금 신청 전조회'},
			{'id':'API_DepDeindLst0500_02'	,'name':'정기예금 신규'					,'explain':'정기예금 신규 서비스'},
			{'id':'API_DepDeinIlst0600'		,'name':'정기적금 신규'					,'explain':'정기적금 신규 서비스'},
			{'id':'API_DepDeindLst0401'		,'name':'세금우대 한도조회'				,'explain':'비과세한도 조회'},
			{'id':'API_DepDeclTran0100'		,'name':'해지가능계좌조회'					,'explain':'해지 가능한 계좌목록 조회'},
			{'id':'API_DepDeclTran0200'		,'name':'해지예상조회'					,'explain':'예적금 해지에 따른 예상금액 및 이자 조회'},
			{'id':'API_DepDeclRevo0300'		,'name':'예적금 해지'						,'explain':'예적금 해지 처리'},
			{'id':'API_DepDeclRevo0201'		,'name':'예적금 해지 선조회'				,'explain':'예적금 해지 선조회'},
			{'id':'API_PrdInfoList0100'		,'name':'예적금상품목록조회'				,'explain':'정기 예금 및 적금 상품목록 조회'},
			{'id':'API_PrdInfoDtil0100'		,'name':'정기예금상품상세조회'				,'explain':'정기예금 이율, 단/복리 등 상품 상세정보 조회'},
			{'id':'API_DepDeindLst0400_03'	,'name':'권유사용자조회'					,'explain':'권유사용자정보 조회'},
			{'id':'API_RacCdacChek0100'		,'name':'정기예금정보입력/체크카드번호조회'	,'explain':'체크카드번호 조회 (체크카드 기반 상품 여부 체크)'},
			{'id':'API_DepDeindLst0500_01'	,'name':'신용정보활용동의전조회'			,'explain':'신용정보활용동의 전조회'},
			{'id':'API_DepDeindLst0500_03'	,'name':'개인(신용)정보관련표준동의서조회'	,'explain':'개인(신용)정보 관련 표준동의서 조회'},
			{'id':'API_DepDeindLst0501'		,'name':'신용정보활용동의본거래'			,'explain':'개인신용정보활용동의 본거래'},
			{'id':'API_PrdInfoDtil0100_01'	,'name':'정기적금상품확인'					,'explain':'정기적금상품 상세정보 조회'}
		]
	}
	,'flow_09'		: {
		'flow_nm'	: '대출 프로세스',
		'flow_data'	: [
			{'id':'API_LonInfoLoan0300'	,'name':'예적금담보대출-계좌조회'							,'explain':'예적금담보계좌조회, 종통 포함(신청 1)'},
			{'id':'API_LonInfoLoan0400'	,'name':'예적금담보대출-원장등록'							,'explain':'예적금담보원장조회등록 종통대출예적금담보원장등록'},
			{'id':'API_LonInfoLoan0401'	,'name':'예적금담보대출-대출고객본인확인 '					,'explain':'인터넷뱅킹대출고객본인확인 종통대출(인터넷뱅킹)대출고객본인확인'},
			{'id':'API_LonInqyDtrn0200'	,'name':'예적금담보대출결과조회'							,'explain':'인터넷뱅킹대출(예적금,종통) 고객본인확인요청 결과조회'},
			{'id':'API_LonInfoLoan0701'	,'name':'예적금담보대출-고객본인확인요청처리'				,'explain':'대출결과조회 - 대출취소'},
			{'id':'API_LonInfoLoan0702'	,'name':'예적금담보대출-대출원장조회등록'					,'explain':'대출결과조회 - 대출실행'},
			{'id':'API_LonInfoSail0300'	,'name':'SGI사잇돌대출-신청'								,'explain':'SGI사잇돌대출신청'},
			{'id':'API_LonRpifTran0200'	,'name':'대출이자납입금액/대출상환 조회'						,'explain':'대출상환조회, 대출이자납입금액조회'},
			{'id':'API_LonRpifPaym0100'	,'name':'대출이자납입-상환계좌 조회'						,'explain':'대출계좌조회'},
			{'id':'API_LonRpifPaym0200'	,'name':'대출이자납입/대출상환 수취인성명조회'				,'explain':'수취인성명조회(당행)'},
			{'id':'API_LonRpifPaym0201'	,'name':'대출이자납입/대출원금상환'							,'explain':'대출원금상환1차, 대출원금상환2차, 대출이자납입1차, 대출이자납입2차'},
			{'id':'API_LonRpifRepy0201'	,'name':'대출원리금상환-종통약정해제'						,'explain':'디지털뱅킹 종통약정해제'},
			{'id':'API_LonRpifRest0100'	,'name':'예금담보대출상계-대상조회'							,'explain':'예금담보대출상계대상조회'},
			{'id':'API_LonRpifRest0200'	,'name':'예적금담보대출상계-전조회'							,'explain':'예적금담보대출상계전조회'},
			{'id':'API_LonRpifRest0300'	,'name':'예적금담보대출상계'								,'explain':'예적금담보대출상계'},
			{'id':'API_LonRpifTore0100'	,'name':'한도증액/감액 - 대상계좌조회'						,'explain':'(종합통장대출)한도증액/감액 - 대상계좌조회'},
			{'id':'API_LonRpifTore0200'	,'name':'종합통장대출한도감액/증액'							,'explain':'(종합통장대출)한도감액/증액'},
			{'id':'API_LonRpifTore0200_01'	,'name':'종합통장대출한도증액'							,'explain':'(종합통장대출)한도증액'},  // 없음
			{'id':'API_LonFdpcList0100'	,'name':'대출만기도래현황'									,'explain':'대출만기도래현황'},
			{'id':'API_LonFdpcUpco0100'	,'name':'대출이자납입기일도래현황'							,'explain':'대출이자납입기일도래현황'},
			{'id':'API_LonDdexList0100'	,'name':'대출기한연장-전조회'								,'explain':'대출기한연장-전조회'},
			{'id':'API_LonDdexList0201'	,'name':'대출기한연장'									,'explain':'대출기한연장'},
			{'id':'API_LonDdexTran0100'	,'name':'대출기한연장이력조회'								,'explain':'대출기한연장이력조회'},
			{'id':'API_LonDdexTran0200'	,'name':'대출기한연장이력조회-상세조회'						,'explain':'대출기한연장이력조회상세조회'},
			{'id':'API_LonWileAppl0100'	,'name':'대출철회및금리인하요구권신청전조회'					,'explain':'대출계약철회및금리안하요구권등록전조회'},
			{'id':'API_LonWileAppl0200'	,'name':'대출계약철회및금리인하요구권등록'					,'explain':'대출계약철회및금리인하요구권등록'},
			{'id':'API_LonWileCncl0100'	,'name':'대출철회및금리인하요구권신청취소전조회'				,'explain':'대출계약철회및금리인하요구권등록취소전조회'},
			{'id':'API_LonWileCncl0200'	,'name':'대출계약철회및금리인하요구권등록취소'				,'explain':'대출계약철회및금리인하요구권등록취소'},
			{'id':'API_LonCaiq0100'		,'name':'대출해지계좌조회'									,'explain':'대출해지계좌조회'},
			{'id':'API_LonWileAppl1000'	,'name':'대출철회및금리인하요구권신청 - 비대면거래번호채번'	,'explain':'대출철회및금리인하요구권신청 - 비대면거래번호채번'}
		]
	}
	,'flow_10'		: {
		'flow_nm'	: '사고 프로세스',
		'flow_data'	: [
			{'id':'API_RacScreList0100'		,'name':'보안카드및OTP사고신고'	,'explain':'보안카드 및 OTP 사고신고 처리'},
			{'id':'API_RacCdacChek0100_01'	,'name':'체크카드사고신고선조회'	,'explain':'체크카드 사고신고 처리 선조회'},
			{'id':'API_RacCdacChek0300'		,'name':'체크카드사고신고'			,'explain':'체크카드 사고신고 처리'},
			{'id':'API_RacCcacList0200'		,'name':'자행수표사고신고'			,'explain':'자행수표사고신고 처리'},
			{'id':'API_RacOtprOtps0100_01'	,'name':'OTP사고회복선거래'		,'explain':'OTP 사고회복 선조회'},
			{'id':'API_RacOtprOtps0300'		,'name':'OTP사고회복본거래'		,'explain':'OTP 사고회복 처리'}
		]
	}
	,'flow_11'		: {
		'flow_nm'	: '실명확인 프로세스',
		'flow_data'	: [
			{'id':'API_ComMony0101_01'	,'name':'비대면 인증정보 등록'		,'explain':'비대면 인증정보 등록'},
			{'id':'API_NomAcco0900_03'	,'name':'비대면 인증대상고객 조회'	,'explain':'비대면 인증대상고객 조회'},
			{'id':'API_ComAddr0101'		,'name':'도로명주소 조회1'			,'explain':'도로명주소 조회1'},
			{'id':'API_ComMony0100_01'	,'name':'비대면 1원이체 인증'		,'explain':'비대면 1원이체 인증'},
			{'id':'API_ComCert0200_01'	,'name':'신분증진위확인'		,'explain':'신분증진위확인'}
		]
	}
	,'flow_12'		: {
		'flow_nm'	: '고객 프로세스',
		'flow_data'	: [
			{'id':'API_NomAcco0400_02'	,'name':'고객정보 조회'	,'explain':'고객정보 조회'},
			{'id':'API_NomAcco0400_01'	,'name':'고객정보 등록'	,'explain':'고객정보 등록'},
			{'id':'API_NomAcco0401_064'	,'name':'고객정보 등록'	,'explain':'고객정보 등록(OK)'},
			{'id':'API_NomAcco0402_064'	,'name':'디지털뱅킹 신분증정보 등록'	,'explain':'디지털뱅킹 신분증정보 등록(OK)'},
			{'id':'API_CusCertColl0300'	,'name':'비과세증빙자료 제출'	,'explain':'비과세증빙자료 제출(OK)'}
		]
	}
	,'flow_13'		: {
		'flow_nm'	: '비대면 수신 프로세스',
		'flow_data'	: [
		   			{'id':'API_NomAcco0400_02'	,'name':'고객정보 조회'	,'explain':'고객정보 조회'},
					{'id':'API_NomAcco0400_01'	,'name':'고객정보 등록'	,'explain':'고객정보 등록'},
           	{'id':'API_NomAcco0700_02'	,'name':'비과세 한도조회'				,'explain':'비과세 한도조회'},
        	{'id':'API_NomAcco0700_03'	,'name':'정기예금 신규상담조회'			,'explain':'정기예금 신규상담조회'},
        	{'id':'API_NomAcco0800_02'	,'name':'적금 신규상담조회'			,'explain':'적금 신규상담조회'},
        	{'id':'API_NomAcco0600_01'	,'name':'예적금 신청'					,'explain':'예적금 신청'},
        	{'id':'API_NomChek0800_01'	,'name':'체크카드 신청'				,'explain':'체크카드 신청'},
        	{'id':'API_CarLotr0100'		,'name':'롯데카드 신청'				,'explain':'롯데카드 신청'},
        	{'id':'API_NomBrea0900'		,'name':'수신-카드상품 진행상태 조회'	,'explain':'수신-카드상품 진행상태 조회'},
        	{'id':'API_NomBrea0700'		,'name':'수신-카드상품 간략조회'		,'explain':'수신-카드상품 간략조회'},
        	{'id':'API_NomAcco0400_03'	,'name':'수신-카드상품 신청취소'		,'explain':'수신-카드상품 신청취소'}
		]
	}
	,'flow_14'		: {
		'flow_nm'	: '전자금융 프로세스',
		'flow_data'	: [
			{'id':'API_NomAcco0900_01'	,'name':'전자금융 이용가능ID조회'		,'explain':'전자금융 이용가능ID조회'},
			{'id':'API_NomAcco0900_02'	,'name':'전자금융 이용 신청'			,'explain':'전자금융 이용 신청'}
		]
	}
	,'flow_15'		: {
		'flow_nm'	: '대출 프로세스',
		'flow_data'	: [
			{'id':'API_NomSign1200_01'	,'name':'대출 신청'					,'explain':'대출 신청'},
			{'id':'API_NomSign1000'		,'name':'대출 신청내역 조회'			,'explain':''},
			{'id':'API_NomSign1001'		,'name':'대출 신청취소'				,'explain':'대출 신청취소/종합통장대출 신청내역 취소'},
			{'id':'API_NomKred0400'		,'name':'햇살론 신청'					,'explain':''},
			{'id':'API_NomSign2900_01'	,'name':'종합통장대출 신청1'			,'explain':''},
			{'id':'API_NomSign3700_01'	,'name':'종합통장대출 신청2'			,'explain':''},
			{'id':'API_NomDask0700'		,'name':'종합통장대출 신청내역 조회'		,'explain':''},
		]
	}
	,'flow_16'		: {
		'flow_nm'	: '전자약정 프로세스',
		'flow_data'	: [
			{'id':'API_NomArrn0400'		,'name':'전자약정 본인확인'			,'explain':'전자약정 본인확인/전자약정 대출목록조회'},
			{'id':'API_NomArrn0500'		,'name':'전자약정 동의서'				,'explain':'전자약정 동의서/전자약정 대출상세조회/전자약정 문서종류 조회/전자약정 전자문서생성 데이터조회'},
			{'id':'API_NomArrn0500_01'	,'name':'전자약정 작성완료'			,'explain':'전자약정 작성완료/전자약정 약정서 부본파일 전송/전자약정 최종 서명완료'}
		]
	}
	,'flow_17'		: {
		'flow_nm'	: '공통 프로세스',
		'flow_data'	: [
			{'id':'API_ComSecu0100'		,'name':'보안카드지시번호요청'			,'explain':'보안카드 지시번호를 요청'},
			{'id':'API_ComSecu0200'		,'name':'보안카드번호확인'				,'explain':'보안카드 지시번호에 대한 입력 번호를 확인'}
			]
	}
	,'flow_18'		: {
		'flow_nm'	: '카카오이체',
		'flow_data'	: [
			{'id':'API_TrnImtrKaka0100_01'	,'name':'카카오이체1단계-송금전조회'						,'explain':'카카오이체1단계-송금전조회 및 간편이체가능여부 조회'},
			{'id':'API_TrnImtrKaka0100_02'	,'name':'카카오이체1단계-송금등록'							,'explain':'카카오이체1단계-송금등록'},
			{'id':'API_TrnImtrKaka0100_03'	,'name':'카카오이체1단계-송금등록(채널)'					,'explain':'카카오이체1단계-송금등록(채널)'},
			{'id':'API_TrnImtrKaka0300'		,'name':'카카오이체3단계-송금등록조회'						,'explain':'카카오이체3단계-송금등록조회 및 접속정보업데이트'},
			{'id':'API_TrnImtrKaka0300_01'	,'name':'카카오이체3단계-수취조회'							,'explain':'카카오이체3단계-송금등록조회 및 수취조회'},
			{'id':'API_TrnImtrKaka0300_02'	,'name':'카카오이체3단계-수취처리'							,'explain':'카카오이체3단계-수취처리 및 이체정보업데이트'},
   	   ]
	}
	,'flow_19'		: {
		'flow_nm'	: '신규 프로세스',
		'flow_data'	: [
			{'id':'API_NomAcco0200_01'		,'name':'비대면수신상품정보조회'						,'explain':'[완료] 비대면수신상품정보조회'},
			{'id':'API_NomSign0400_01'		,'name':'은행서비스정보조회'							,'explain':'[완료] 은행서비스정보조회'},
			{'id':'API_NomAcco0300_01'		,'name':'비대면수신상품정보조회'						,'explain':'[완료] 비대면수신상품정보조회'},
			{'id':'API_NomAcco1200'			,'name':'비대면예적금금리정보'							,'explain':'[완료] 비대면예적금금리정보'},
			{'id':'API_NomAcco1401_01'		,'name':'전체직종 검색'								,'explain':'[완료] 전체직종 검색'},
			{'id':'API_NomAcco1401_02'		,'name':'하위직종 검색'								,'explain':'[완료] 하위직종 검색'},
			{'id':'API_NomAcco0700_01'		,'name':'정기예금 신청'								,'explain':'[완료] 정기예금 신청'},
			{'id':'API_NomAcco0600_02'		,'name':'정기예금 신규상담조회'							,'explain':'[완료] 정기예금 신규상담조회'},
			{'id':'API_NomAcco0700_04'		,'name':'비대면 실명확인조회'							,'explain':'[완료] 비대면 실명확인조회'},
			{'id':'API_NomAcco2000'			,'name':'디지털뱅킹_비대면수신상품등록LOG'				,'explain':'[완료] 디지털뱅킹_비대면수신상품등록LOG'},
			{'id':'API_NomJoin0300_02'		,'name':'비대면수신상품정보(전자금융개설)'				,'explain':'[완료] 비대면수신상품정보(전자금융개설)'},
			{'id':'API_NomChek0200_01'		,'name':'비대면카드상품정보'							,'explain':'[완료] 비대면카드상품정보'},
			{'id':'API_NomLotr0300_01'		,'name':'롯데카드신청'								,'explain':'[완료] 롯데카드신청'},
			{'id':'API_ComMony0100_02'		,'name':'비대면 인증정보 등록'							,'explain':'사용안함. (API_ComMony0101_01 대체.)'},
			{'id':'API_ComScra0100'			,'name':'스크래핑사전데이타조회(휴일여부조회)'			,'explain':'[완료] 스크래핑사전데이타조회(휴일여부조회)'},
			{'id':'API_NomKred0200'			,'name':'대출상품조회'								,'explain':'[완료] 대출상품조회'},
			{'id':'API_NomSign0600'			,'name':'신용대출신청/가입고객확인'						,'explain':'[완료] 신용대출신청/가입고객확인'},
			{'id':'API_NomSign0100_01'		,'name':'신분증이미지전송'								,'explain':'[완료] 신분증이미지전송'},
			{'id':'API_NomSign0601'			,'name':'신용대출신청/고객정보저장'						,'explain':'[완료] 신용대출신청/고객정보저장'},
			{'id':'API_NomSign0704'			,'name':'입금계좌수취인조회'							,'explain':'[ERROR] 입금계좌수취인조회'},
			{'id':'API_RacReacList0100_01'	,'name':'사고신고가능계좌조회'							,'explain':'[완료] 사고신고가능계좌조회'},
			{'id':'API_RacReacList0100'		,'name':'디지털뱅킹 사고신고'							,'explain':'[ERROR] 디지털뱅킹 사고신고'},
			{'id':'API_RacCdacList0100'		,'name':'디지털뱅킹 IC카드 사고신고'					,'explain':'[완료] 디지털뱅킹 IC카드 사고신고'},
			{'id':'API_RacCcacList0100'		,'name':'자기앞수표신고'								,'explain':'[완료] 자기앞수표사고신고가능내역조회'},
			{'id':'API_RacCcacTran0200'		,'name':'자기앞수표사고신고_사고신고내역조회'			,'explain':'[로그정보없음] 자기앞수표사고신고_사고신고내역조회'},
			{'id':'API_LonInfoInfo1200'		,'name':'인터넷대출신청'								,'explain':'[ERROR] 인터넷대출신청'},
			{'id':'API_LonInfoSail0200'		,'name':'SGI사잇돌대출-지점조회'						,'explain':'[완료] SGI사잇돌대출-지점조회'},
			{'id':'API_LonInqyTran0200'		,'name':'인터넷대출신청결과조회'						,'explain':'[완료] 인터넷대출신청결과조회'},
			{'id':'API_DepDeindLst0400_04'	,'name':'과세구분코드 조회'							,'explain':'[완료] 과세구분코드 조회'},
			{'id':'API_DepDeindLst0401_01'	,'name':'비과세종합저축 한도조회'						,'explain':'[완료] 비과세종합저축 한도조회'},
			{'id':'API_DepDeinIlst0502'		,'name':'예적금상품 상품확인'							,'explain':'[로그정보없음] 예적금상품 상품확인'},
			{'id':'API_DepDeclRevo0101'		,'name':'해지 가능계좌 조회'							,'explain':'[완료] 해지 가능계좌 조회'},
			{'id':'API_DepDeclRevo0100'		,'name':'전자금융사기예방 조회'							,'explain':'[완료] 전자금융사기예방 조회'},
			{'id':'API_DepDeclRevo0200'		,'name':'예적금 해지_선거래(고객연락처 조회)'				,'explain':'[완료] 예적금 해지_선거래(고객연락처 조회)'},
			{'id':'API_DepTran0100_1'		,'name':'예적금 해지 계좌 조회'							,'explain':'[완료] 예적금 해지 계좌 조회'},
			{'id':'API_DepDech0100'			,'name':'적금 납입일변경 가능 계좌 조회'					,'explain':'[완료] 적금 납입일변경 가능 계좌 조회'},
			{'id':'API_DepDech0200'			,'name':'적금 납입일 변경 선조회'						,'explain':'[완료] 적금 납입일 변경 선조회 (TRTM_DVCD:0조회,:1변경 '},
			{'id':'API_DepDech0300'			,'name':'적금 납입일 변경 처리'							,'explain':'[완료] 적금 납입일 변경 처리'},
			{'id':'API_DepDeauRegi0100_01'	,'name':'자동만기연장대상조회'							,'explain':'[완료] 자동만기연장대상조회'},
			{'id':'API_DepDeauRegi0200'		,'name':'자동만기연장등록전조회'						,'explain':'[완료] 자동만기연장등록전조회'},
			{'id':'API_DepDeauRegi0400'		,'name':'자동만기연장 등록 및 해제'						,'explain':'[로그정보없음] 자동만기연장 등록 및 해제'},
			{'id':'API_TrnSmatAtsr0200'		,'name':'지역별ATM목록'								,'explain':'[완료] 지역별ATM목록'},
			{'id':'API_TrnImtrRigt0100_04'	,'name':'간편이체시작 DB조회및 업데이트'					,'explain':'[완료] 간편이체시작 DB조회및 업데이트'},
			{'id':'API_TrnImtrRigt0100_05'	,'name':'혼합형적금계좌 체크'							,'explain':'[완료] 혼합형적금계좌 체크'},
			{'id':'API_TrnImtrRigt0105_01'	,'name':'보이스피싱정보 수집'							,'explain':'[로그정보없음] 보이스피싱정보 수집 '},
			{'id':'API_TrnImtrRigt0200_02'	,'name':'간편이체완료 DB업데이트'						,'explain':'[로그정보없음] 간편이체완료 DB업데이트'},
			{'id':'API_TrnImtrTran0100_01'	,'name':'즉시이체 (당/타행)거래내역조회'					,'explain':'[완료] 즉시이체 (당/타행)거래내역조회'},
			{'id':'API_TrnAutrRevo0300_01'	,'name':'당/타행 비밀번호 확인(인뱅/스뱅)'				,'explain':'[완료] 당/타행 비밀번호 확인'},
			{'id':'API_comCert0100_03'		,'name':'전자서명 db저장 및 출금동의 증빙자료'			,'explain':'[ERROR]전자서명 db저장 및 출금동의 증빙자료'},
			{'id':'API_IbaDtrn0100'			,'name':'지연이체서비스조회'							,'explain':'[완료] 지연이체서비스조회'},
			{'id':'API_TrnDetrList0100_02'	,'name':'수취조회 및 이체가능금액 조회'					,'explain':'[완료] 수취조회 및 이체가능금액 조회'},
			{'id':'API_TrnDetrList0200_01'	,'name':'이체 실행 및 자주쓰는계좌 등록'					,'explain':'[로그정보없음] 이체 실행 및 자주쓰는계좌 등록'},
			{'id':'API_TrnDetrList0200_02'	,'name':'지연이체서비스 본인인증등록'					,'explain':'[로그정보없음] 지연이체서비스 본인인증등록'},
			{'id':'API_TrnDetrList0300_01'	,'name':'자주쓰는계좌 등록'							,'explain':'[로그정보없음] 자주쓰는계좌 등록'},
			{'id':'API_TrnDetrCncl0100'		,'name':'지연이체처리내역조회'							,'explain':'[완료] 지연이체처리내역조회'},
			{'id':'API_TrnDetrCncl0200_01'	,'name':'지연이체처리취소'								,'explain':'[로그정보없음] 지연이체처리취소'},
			{'id':'API_IbaDeptJore0100'		,'name':'입금지정계좌목록조회'							,'explain':'[완료] 입금지정계좌목록조회'},
			{'id':'API_LogIdfn0300_01'		,'name':'아이디찾기 선조회 (아이디찾기->전화번호찾기)'		,'explain':'[완료] 아이디찾기 선조회 (아이디찾기->전화번호찾기)'},
			{'id':'API_LogIdfn0200'			,'name':'아이디찾기 ARS인증용 연락처조회'				,'explain':'[완료] 아이디찾기 ARS인증용 연락처조회'},
			{'id':'API_LogUpwl0100_01'		,'name':'사용자비밀번호 5회 오류 해체'					,'explain':'[완료] 사용자비밀번호 5회 오류 해체'},
			{'id':'API_SeuAdsvJoin0200_02'	,'name':'추가인증서비스 가입정보를 조회'					,'explain':'[완료] 추가인증서비스 가입정보를 조회'},
			{'id':'API_SeuOotp0100_01'		,'name':'고객OTP정보조회'								,'explain':'[완료] 고객OTP정보조회'},
			{'id':'API_PA_OtpTxCreate'		,'name':'사설인증 Otp비교용 트랜잭션 생성 '				,'explain':'[완료] 사설인증 Otp비교용 트랜잭션 생성 '},
			{'id':'API_PA_OtpTxSign'		,'name':'사설인증 Otp비교용 서명검증'					,'explain':'[완료] 사설인증 Otp비교용 서명검증'},
			{'id':'API_SeuPinnPinn0100'		,'name':'사설인증관리정보를 처리(핀, 지문, 패턴)'		,'explain':'[완료] 사설인증관리정보를 처리(핀, 지문, 패턴)'},
			{'id':'API_CerIssu0200_02'		,'name':'공인인증서 PC지정여부 확인'					,'explain':'[로그정보없음] 공인인증서 PC지정여부 확인'},
			{'id':'API_ComGetRegiBank'		,'name':'가입저축은행 조회'							,'explain':'[완료] 가입저축은행 조회'},
			{'id':'API_CusCertDepo0200'		,'name':'예금잔액증명서_발급신청'							,'explain':'[완료] 예금잔액증명서_발급신청'}
		]
	}
	,'flow_20'		: {
		'flow_nm'	: '신규 프로세스2',
		'flow_data'	: [
		    {'id':'API_CusCertDepo0200'		,'name':'예금잔액증명서_발급신청 조회'						,'explain':'[로그정보없음] 예금잔액증명서_발급신청 조회'},
			{'id':'API_CusCertColl0200'		,'name':'금융소득종합과세 조회및발급'						,'explain':'[로그정보없음] 금융소득종합과세 조회및발급'},
			{'id':'API_CusCertColl0100'		,'name':'원천징수영수증 조회및발급'							,'explain':'[로그정보없음] 원천징수영수증 조회및발급'},
			{'id':'API_CusCertFine0200'		,'name':'금융거래확인서 조회및발급'							,'explain':'[로그정보없음] 금융거래확인서 조회및발급'},
			{'id':'API_CusCertDebt0200'		,'name':'부채잔액증명서 조회및발급'							,'explain':'[로그정보없음] 부채잔액증명서 조회및발급'},
			{'id':'API_NomSign1100'			,'name':'대출신청/고객정보입력/가입고객확인'				,'explain':'[로그정보없음] 대출신청/고객정보입력(신용대출/사잇돌)/가입고객확인'},
			{'id':'API_NomSign1100_01'		,'name':'대출신청/고객정보입력저장'							,'explain':'[로그정보없음] 대출신청/고객정보입력(신용대출/사잇돌)저장'},
			{'id':'API_NomArrn0400_01'		,'name':'전자약정/동의서'									,'explain':'[로그정보없음] 전자약정/동의서'},
			{'id':'API_LonInfoLoan0700'		,'name':'예적금담보대출실행'								,'explain':'[로그정보없음] 예적금담보대출실행'},
			{'id':'API_NomSign0100'			,'name':'대출상품서비스은행조회'							,'explain':'[로그정보없음] 대출상품서비스은행조회'},
			{'id':'API_LogIdfn0400'			,'name':'디지털뱅킹 전자금융 ID조회 (OpenAPI)'				,'explain':'[완료] 디지털뱅킹 전자금융 ID조회 (OpenAPI)'},
			{'id':'API_ComSerc0100'			,'name':'추천인조회'										,'explain':'[완료] 추천인조회'},
			{'id':'API_InqTrhi0100_02'		,'name':'기간별대출거래내역'								,'explain':'기간별대출거래내역'},
			{'id':'API_ComPushAddUser'		,'name':'푸시 사용자 등록'									,'explain':'푸시 사용자 등록'},
			{'id':'API_IbaSuadStad0100'		,'name':'거래중지계좌관리 - 재개신청 대상조회'				,'explain':'거래중지계좌관리 - 재개신청 대상조회'},
			{'id':'API_IbaSuadStad0200'		,'name':'거래중지계좌관리 - 재개신청 전조회'				,'explain':'거래중지계좌관리 - 재개신청 전조회'},
			{'id':'API_IbaSuadStad0300'		,'name':'거래중지계좌관리 - 재개신청'						,'explain':'거래중지계좌관리 - 재개신청'},
			{'id':'API_IbaSuadStad0400'		,'name':'거래중지계좌관리 - 해지신청 전조회'				,'explain':'거래중지계좌관리 - 해지신청 전조회'},
			{'id':'API_IbaSuadStad0500'		,'name':'거래중지계좌관리 - 해지신청 본인확인'				,'explain':'거래중지계좌관리 - 해지신청 본인확인'},
			{'id':'API_IbaSuadStad0600'		,'name':'거래중지계좌관리 - 해지신청'						,'explain':'거래중지계좌관리 - 해지신청'},
			{'id':'API_IbaSuadStad0700'		,'name':'거래중지계좌관리 - 거래중지 계좌목록조회'			,'explain':'거래중지계좌관리 - 거래중지 계좌목록조회'},
			{'id':'API_IbaDrcl0100'			,'name':'뱅킹관리 - 출금계좌 등록변경'						,'explain':'출금계좌 등록변경'},
			{'id':'API_stampPublicKey'		,'name':'QR공개키요청'	 					,'explain':'QR공개키요청'},
			{'id':'API_ComMail'				,'name':'이메일전송'	 					,'explain':'이메일전송'}
		]
	},
	
	'flow_21'		: {
		'flow_nm'	: '고객정보관리 / 자주쓰는계좌관리',
		'flow_data'	: [
		    {'id':'API_CusUaca0500'		,'name':'자주쓰는계좌관리 - 삭제완료'						,'explain':'자주쓰는계좌관리 - 삭제완료'},
			{'id':'API_CusUaca0100'		,'name':'자주쓰는계좌관리 - 목록조회'						,'explain':'자주쓰는계좌관리 - 목록조회'},
			{'id':'API_CusUaca0300'		,'name':'자주쓰는계좌관리 - 등록'							,'explain':'자주쓰는계좌관리 - 등록'},
			{'id':'API_CusUaca0200_01'	,'name':'자주쓰는계좌관리 - 단순수취인조회'					,'explain':'자주쓰는계좌관리 - 단순수취인조회'},
		]
	}
};

var enCdToKrNm	= {
	'NECT_WRCN_KIND_NO'					:'비대면동의서종류번호',
	'ABR_LOS_RBR_YN_DVCD'				:'국외분실도난여부구분코드',
	'ACCO_FLAG'							:'자주쓰는계좌',
	'ACCO_KNCD'							:'계좌종류',
	'ACCO_PWD'							:'계좌비밀번호',
	'ACDT_APLC_DTM'						:'사고신고일시',
	'ACDT_CHCK_CTBL'					:'사고수표권종',
	'ACDT_DCL_CRCT_DSTC'				:'사고신고정정구분',
	'ACDT_DCL_DETL'						:'사고신고내역',
	'ACHN_LMIT_AMT'						:'변경후한도금액',
	'ACHN_PWD'							:'변경후비밀번호',
	'ACML_AMT'							:'누적금액',
	'ACNO'								:'계좌번호',
	'ACPT_DSTC1'						:'접수구분',
	'ACPT_DT'							:'접수일자',
	'ACTNO'								:'계좌번호',
	'ADDR_DSTC'							:'주소구분',
	'ADDR_INQ_RESP_CD'					:'주소조회응답코드',
	'ADDR_REF_ITEM_NM'					:'주소참조항목명',
	'ADDR_TP'							:'주소타입',
	'ADDT_USER_IDNT_CD'					:'추가사용자식별코드',
	'AF_DD1_WTCH_LMIT_AMT'				:'변경후1일출금한도금액',
	'AF_TI1_WTCH_LMIT_AMT'				:'변경후1회출금한도금액',
	'AFRP_SAMT_N18'						:'상환총금액',
	'AGPP_FILE_STCD'					:'약정서부본상태',
	'AGRM_ACNO'							:'약정계좌번호',
	'ALS'								:'별칭',
	'ALTALK_RCMS_YN'					:'알림톡수신여부',
	'ANIN_DVCD'							:'연소득구분코드',
	'APFT_ACPT_BOCD'					:'신청서접수점코드',
	'APL_INRT'							:'적용이율',
	'APL_INRT2'							:'적용이율2',
	'APLC_NM'							:'신고자명',
	'APLC_NRBRNO_INQ'					:'신고자주민번호',
	'APLC_TLNO1'						:'신고자전화번호1',
	'APLC_TLNO2'						:'신고자전화번호',
	'APLC_TLNO3'						:'신고자전화번호3',
	'ATMT_EXPT_EXTS_YN'					:'자동만기연장여부',
	'ATMT_REG_DVCD'						:'자동등록구분',
	'ATNT_ACDT_DSTC1'					:'주의사고구분',
	'ATPAY_CNTP_BK_ACNO'				:'자동납부상대은행계좌번호',
	'ATPAY_CNTP_BKCD'					:'자동납부상대은행코드',
	'ATPAY_DSTC'						:'자동납부구분',
	'ATSH_EDDT'							:'인증서종료일자',
	'ATSH_ISS_DT'						:'인증서발급일자',
	'ATSH_ISS_INST_VAL'					:'인증서발급기관값',
	'ATSH_ISS_YN'						:'인증서발급여부',
	'ATSH_KNCD'							:'인증서종류',
	'ATSH_MNGNO'						:'인증서관리번호',
	'ATTR_DSGT_DT'						:'자동이체지정일',
	'ATTR_DT'							:'자동이체날짜',
	'ATTR_REG_N1'						:'자동이체등록',
	'ATTR_WTCH_ACNO_C14'				:'자동이체출금계좌번호',
	'ATTR_YN'							:'자동이체여부',
	'BANK_CD'							:'저축은행코드',
	'BANKCODE'							:'저축은행코드',
	'BC_ACDT_CD'						:'비씨카드사고코드',
	'BC_ACDT_CD2'						:'비씨카드사고코드',
	'BC_ACPT_DVCD'						:'비씨카드접수구분코드',
	'BC_ACPT_NO'						:'비씨카드접수번호',
	'BC_BNKB_BLNC_MRK_YN_DVCD'			:'비씨카드통장잔액표시여부구분코드',
	'BC_MBCD_PRIO_ISS_YN'				:'비씨카드모바일카드우선발급여부',
	'BC_WRCN_ACPT_CNT'					:'BC동의서접수건수',
	'BCHN_ACNO'							:'변경전계좌번호',
	'BCHN_LMIT_AMT'						:'변경전한도금액',
	'BCHN_PWD'							:'변경전비밀번호',
	'BE_DD1_WTCH_LMIT_AMT'				:'변경전1일출금한도금액',
	'BE_TI1_WTCH_LMIT_AMT'				:'변경전1회출금한도금액',
	'BIL_SEND_MTH_DVCD'					:'청구서발송방법구분코드',
	'BKCD'								:'은행코드',
	'BLAD_ADDR'							:'청구지주소',
	'BLAD_ADDR_DVCD'					:'청구지주소구분코드',
	'BLAD_ADDR_PNU_VAL'					:'청구지주소PNU값',
	'BLAD_ADDR_REF_CNTN'				:'청구지주소참조내용',
	'BLAD_BSIC_ADDR'					:'청구지기본주소',
	'BLAD_DTAD'							:'청구지상세주소',
	'BLAD_ZPCD'							:'청구지우편번호',
	'BLDG_MNGNO'						:'건물관리번호',
	'BO_NO'								:'지점번호',
	'BOCD'								:'지점코드',
	'BRNO'								:'사업자등록번호',
	'BSDT'								:'기준일자',
	'BSIC_ADDR_C200'					:'기본주소',
	'BUSI_KIND'							:'사업자종류',
	'BUSI_LIST'							:'BUSI_LIST',
	'BUSI_LIST_CNT'						:'사업자등록내역건수',
	'BUSI_REG_CERT_ISS_NO'				:'사업자등록증명서발급번호',
	'CALC_CNTR_AMT'						:'계산계약금액',
	'CALC_CNTR_AMT2'					:'계산계약금액2',
	'CALC_DVCD'							:'계산구분코드',
	'CALC_MN_PYMN_AMT'					:'계산월불입금액',
	'CALC_MN_PYMN_AMT2'					:'계산월불입금액2',
	'CAN_FLAG'							:'취소플래그',
	'CAN_NECT_TRN_NO'					:'취소대상비대면거래번호',
	'CAN_POSB_STS_YN'					:'취소가능상태여부',
	'CAN_SBCD'							:'취소대상저축은행',
	'CAN_TRGT_AMT'						:'취소대상금액',
	'CAN_TRGT_PROP_DT'					:'취소대상신청일자',
	'CAN_TRGT_TFNO'						:'취소대상담당직원국번호',
	'CAN_TRGT_TSNO'						:'취소대상담당직원서비스번호',
	'CAN_TRGT_TVNO'						:'취소대상담당직원개별번호',
	'CANO'								:'카드번호',
	'CARD_STMT_INST_BKCD'				:'카드결제기관은행코드',
	'CASH_CARD_FNCT_USE_DVCD'			:'현금카드기능사용구분코드',
	'CASH_CARD_UZ_STPL_AGR_YN_DVCD'		:'현금카드이용약관동의여부구분코드',
	'CCW_CD'							:'시군구코드',
	'CDD_IDT_CNFR_CERT_DVCD'			:'신원확인증명서코드(CDD)',
	'CDD_IDT_CNFR_CERT_ISS_DT'			:'신원확인증명서발급일자(CDD)',
	'CDD_IDT_CNFR_CERT_ISS_INST'		:'신원확인증명서발급기관(CDD)',
	'CDD_JBCF'							:'직종(CDD)',
	'CDD_OCPT_DVCD'						:'직업구분코드(CDD)',
	'CDD_OCPT_ETC'						:'직업구분기타(CDD)',
	'CDD_REXC_DUE_DT'					:'CDD재수행도래일자',
	'CDD_RSDN_DVCD'						:'거주구분코드(CDD)',
	'CERT_SERIAL'						:'인증서시리얼',
	'CHANNEL'							:'접속채널',
	'CHCK_END_NO'						:'수표종료번호',
	'CHCK_SAMT'							:'수표합계금액',
	'CHCK_STRN_NO'						:'수표시작번호',
	'CHCK_UNIT_AMT'						:'수표단위금액',
	'CHCR_ACDT_DCL_ACPT_NO'				:'체크카드사고신고접수번호',
	'CHCR_ALNC_CO_CD'					:'체크카드제휴업체코드',
	'CHNG_PSWD'							:'변경비밀번호',
	'CHRG_BZWR_NM'						:'담당업무명',
	'CLSC_CD'							:'종별코드',
	'CMBB_ACNO'							:'종통계좌번호',
	'CMMD_ACNO'							:'보통예금계좌번호',
	'CMMD_MNRC_AMT_N18'					:'보통예금입금금액',
	'CMP_NM'							:'회사명',
	'CMPH_BNKB_PWD'						:'이용자비밀번호',
	'CMPL_STS'							:'완료상태',
	'CMPY_YN'							:'완제여부',
	'CMS_ACNO'							:'CMS계좌번호',
	'CMS_AGPP_FILE_LEN'					:'CMS약정서파일길이',
	'CMS_BKCD'							:'CMS은행코드',
	'CMS_DIVISION'						:'CMS이체구분',
	'CMS_FILE'							:'약정서부본파일',
	'CMS_FILE_KND'						:'약정서부본파일종류',
	'CMS_FILE_NM'						:'약정서부본파일명',
	'CMS_IOMN_INDV_INFO_AGR_YN'			:'CMS입출금개인정보동의여부',
	'CMS_IOMN_THPR_UZ_AGR_YN'			:'CMS입출금제3자이용동의여부',
	'CMS_IOMN_UNQ_IDNT_INFO_AGR_YN'		:'CMS입출금고유식별정보동의여부',
	'CMS_YN'							:'CMS신청여부',
	'CNFR_PSWD'							:'확인비밀번호',
	'CNPD_DAYS'							:'계약기간일',
	'CNPD_DCNT'							:'계약일수',
	'CNPD_MMCO'							:'계약월수',
	'CNPD_MNTH'							:'계약기간월',
	'CNPD_N3'							:'계약기간',
	'CNPL'								:'연락처',
	'CNSG_GRNY_OCPT_CLCD'				:'수탁보증직업분류코드',
	'CNT'								:'페이지당건수',
	'CNT_N2'							:'건수',
	'CNT1'								:'건수',
	'CNT2'								:'건수',
	'CNTA_KND_C1'						:'연락구분',
	'CNTA_TLNO'							:'연락전화번호',
	'CNTA_TLNO_C13'						:'연락전화번호',
	'CNTR_AMT'							:'계약금액',
	'CNTR_AMT_N15'						:'계약금액',
	'CNTR_DVCD'							:'계약구분코드',
	'CO_NO'								:'업체번호',
	'CPNO'								:'휴대전화번호',
	'CPT_USG_CNTN'						:'자금용도내용',
	'CPT_USG_DVCD'						:'자금용도구분코드',
	'CRFC_DN_VAL'						:'공인인증서DN값',
	'CRIF_COLT_MNDR_AGR_YN'				:'신용정보수집필수동의여부',
	'CRIF_COLT_SLCT_AGR_YN'				:'신용정보수집선택동의여부',
	'CRIF_INQ_AGR_YN'					:'신용정보조회동의여부',
	'CRIF_MRKN_ALL_MTR'					:'신용정보활용동의(전체)',
	'CRIF_MRKN_COLT_UZ_MTR'				:'신용정보마케팅수집이용사항',
	'CRIF_MRKN_OFR_MTR'					:'신용정보마케팅제공사항',
	'CRIF_OFR_DVCD'						:'개인정보3자제공동의여부',
	'CRIF_OFR_MNDR_AGR_YN'				:'신용정보제공필수동의여부',
	'CRIF_UZ_DVCD'						:'개인정보수집이용동의여부',
	'CSNO'								:'고객번호',
	'CSNO_INQ'							:'고객번호',
	'CUR_PAGE'							:'현재페이지',
	'CUST_ADDR'							:'기고객주소',
	'CUST_CNTA_DVCD'					:'고객연락구분코드',
	'CUST_EML_COLT_AGR_YN'				:'고객이메일수집동의여부',
	'CUST_ENSN_NM'						:'고객영문명',
	'CUST_INPT_ANL_INCM_AMT'			:'고객입력연간소득금액',
	'CUST_NM'							:'고객명',
	'CUST_REG_EMAD'						:'고객등록이메일주소',
	'CUST_REG_PRGS_YN'					:'고객등록진행여부',
	'CUST_REG_YN'						:'고객등록진행여부',
	'CUST_TLNO'							:'고객전화번호',
	'CUSTNM_C50'						:'성명',
	'DBTR_CUST_IDNT_INFO_AGR_YN'		:'채무자고객식별정보동의여부',
	'DD1_TRNF_LMIT'						:'1일이체한도',
	'DD1_TRNF_LMIT_AMT'					:'1일이체한도금액',
	'DEF_DISTANCE'						:'DEF_DISTANCE',
	'DENL_RSN_GDNC_YN'					:'거절사유안내여부',
	'DEPO_TRN_KNCD_1'					:'수신거래종류코드_1',
	'DEPR'								:'예금주',
	'DEPR_NM'							:'예금주명',
	'DEPR_NM_20'						:'예금주명',
	'DG2_EVPN'							:'자주쓰는계좌flag',
	'DIMR_PRGS_STCD'					:'이기종진행상태코드',
	'DLAY_EXPT_DT_C8'					:'연기만기일',
	'DM_SEND_DVCD'						:'DM발송구분코드',
	'DM_YN'								:'DM수신동의여부',
	'DMFR_DVCD'							:'국내외구분코드',
	'DN'								:'인증서DN',
	'DOC_CNT'							:'문서건수',
	'DPSY_AMT_N15'						:'예치금액',
	'DRNO_C20'							:'운전면허번호',
	'DRVN_LCNS_CHK_NO'					:'운전면허체크번호',
	'DTAD'								:'상세주소',
	'DTL_ADDR_C200'						:'상세주소',
	'DVCD'								:'구분코드',
	'EDDT'								:'종료일자',
	'EDRN'								:'EDRN',
	'EKD_WRCN_ACPT_CCNT'				:'각종동의서접수건수',
	'ELEC_FNTR_BSIC_STPL_AGR_DVCD'		:'전자금융거래기본약관동의구분코드',
	'ELEC_FNTR_HSTR_STCD'				:'전자금융거래이력상태코드',
	'ELEC_SGNR_DATA_ORCP_CNTN'			:'세션ID',
	'ELEC_SGNR_MSG_ORCP_CNTN'			:'클라이언트IP',
	'ELFN_STPL_AGR_YN'					:'전자금융약관동의여부',
	'EMAD'								:'이메일주소',
	'EMAIL_YN'							:'이메일수신동의여부',
	'EML_ACCP_AGR_DVCD'					:'이메일수령동의구분코드',
	'EML_RCMS_YN'						:'이메일수신여부',
	'EML_SEND_STCD'						:'메일발송상태',
	'ENCM_DT'							:'입사일자',
	'ENSN_NM'							:'영문명',
	'ENTR_AMT'							:'저축종류별가입금액',
	'ENTR_CUST_DVCD'					:'가입고객구분코드',
	'ERR_NTM'							:'오류횟수',
	'ETC_INFO'							:'기타정보',
	'EXMT_CD'							:'면제코드',
	'EXMT_CNT'							:'면제건수',
	'EXPT_DT'							:'만기일자',
	'EXST_CUST_YN'						:'기존고객여부',
	'FEE_5'								:'수수료5자리',
	'FEE_7'								:'수수료7자리',
	'field1'							:'자주쓰는계좌',
	'FILE_DVCD'							:'파일구분코드',
	'FILE_NAME'							:'파일명',
	'FILLER'							:'FILLER',
	'FILLER_10'							:'filler',
	'FILLER0'							:'FILLER',
	'FILLER1'							:'FILLER',
	'FILLER2'							:'FILLER',
	'FILLER3'							:'FILLER',
	'FILLER4'							:'FILLER',
	'FILLER5'							:'FILLER',
	'FILLER6'							:'FILLER',
	'FILLER7'							:'FILLER',
	'FILLER8'							:'FILLER',
	'FILLER9'							:'FILLER',
	'FLAG'								:'플래그',
	'FRGN_DVCD'							:'외국인구분코드',
	'FRST_OPNG_DT_4'					:'최초개시일자',
	'FRT_PWD'							:'초기비밀번호',
	'GATHER_INFO'						:'수집정보유형',
	'GBPR_LMTD_DSTC'					:'범용한정구분',
	'GRNO'								:'지로번호',
	'GRNY_TERM_EDDT'					:'보증기간종료일자',
	'GRNY_TERM_STDT'					:'보증기간시작일자',
	'HLIN_BZPL_NM'						:'건강보험사업장명',
	'HLIN_EDDT'							:'건강보험납부조회종료년월',
	'HLIN_LIST'							:'HLIN_LIST',
	'HLIN_LIST_CNT'						:'건강보험월납부내역건수',
	'HLIN_PAYM_DETL_DTLS_USG_DVCD'		:'건강보험납부내역세부용도구분코드',
	'HLIN_PAYM_DETL_ISS_NO'				:'건강보험납부내역발급번호',
	'HLIN_PAYM_DETL_USE_PPCD'			:'건강보험납부내역사용용도코드',
	'HLIN_PAYM_ISS_DT'					:'건강보험납부발급일자',
	'HLIN_PAYR_NO'						:'건강보험납부자번호',
	'HLIN_PAYT_SBSR_GB'					:'건강보험납부가입자구분코드',
	'HLIN_QLFC_ACQS_DT'					:'건강보험자격취득일자',
	'HLIN_QLFC_FRFT_DT'					:'건강보험자격상실일자',
	'HLIN_QLFC_GNLS_ISS_DT'				:'건강보험자격득실발급일자',
	'HLIN_QLFC_GNLS_ISS_NO'				:'건강보험자격득실발급번호',
	'HLIN_SBSR_DSTC_CNTN'				:'건강보험가입자구분내용',
	'HLIN_SBSR_DVCD'					:'건강보험가입자구분코드',
	'HLIN_STDT'							:'건강보험납부조회시작년월',
	'HLIN_YNTA_NTF_AMT'					:'건강보험연말정산고지금액',
	'HLIN_YNTA_PAYM_AMT'				:'건강보험연말정산납부금액',
	'HNDV_BO_N7'						:'교부지점',
	'HNDV_DT'							:'교부일자',
	'HSNG_OWN_DVCD'						:'주택소유구분코드',
	'ID'								:'이용자ID',
	'IMMD_TRNF_ACCO_CNT'				:'즉시이체계좌건수',
	'IMMD_TRNF_ACCO_REG_YN'				:'즉시이체계좌등록여부',
	'IMMD_TRNF_DD1_LMIT'				:'즉시이체1일한도',
	'IMPR_ALTX_SUM_N18'					:'수입제세합계',
	'IN_CNT'							:'IN_CNT',
	'IN_CNT1'							:'IN_CNT1',
	'IN_CNT2'							:'IN_CNT2',
	'IN_REC'							:'IN_REC',
	'IN_REC1'							:'IN_REC1',
	'IN_REC2'							:'IN_REC2',
	'IN_REC3'							:'IN_REC3',
	'IN_REC4'							:'IN_REC4',
	'IN_REC5'							:'IN_REC5',
	'INBN_CUST_CNFR_SRNO'				:'인터넷뱅킹고객확인일련번호',
	'INBN_ID_C12'						:'인터넷뱅킹ID',
	'INBN_ID_PRE_EXIS_YN'				:'인터넷뱅킹ID기존재여부',
	'INCM_CMPTN_BSDT'					:'기준일자',
	'INDV_BUSI_FRNM_NM'					:'개인사업자상호명',
	'INDV_CORP_DSTC'					:'개인법인구분코드',
	'INDV_CORP_DSTC_CD'					:'개인법인구분코드',
	'INDV_ENTP_DVCD'					:'개인기업구분코드',
	'INDV_INFO_AGR_MTCD'				:'개인정보동의방법코드',
	'INDV_INFO_COLT_UZ_AGR_DVCD'		:'개인정보수집이용동의구분코드',
	'INDV_INFO_COLT_UZ_AGR_YN'			:'개인정보수집이용동의여부',
	'INDV_INFO_DM_AGR_YN'				:'개인정보DM동의여부',
	'INDV_INFO_EML_AGR_YN'				:'개인정보이메일동의여부',
	'INDV_INFO_LTRS_MSG_AGR_YN'			:'개인정보문자메시지동의여부',
	'INDV_INFO_OFR_AGR_DVCD'			:'개인정보제공동의구분코드',
	'INDV_INFO_TEL_AGR_YN'				:'개인정보전화동의여부',
	'INDV_NEW_TRN_PRPS_DVCD'			:'개인신규거래목적구분코드',
	'INDV_NEW_TRN_PRPS_ETC_CNTN'		:'개인신규거래목적기타내용',
	'INDV_NEW_TRN_PRPS_INPM_PAYM_YN'	:'개인신규거래목적보험료납부여부',
	'INDV_NEW_TRN_PRPS_MNPB_PAYM_YN'	:'개인신규거래목적카드대금납부여부',
	'INDV_NEW_TRN_PRPS_PBTX_PAYM_YN'	:'개인신규거래목적공과금납부여부',
	'INDV_STND_OCPT_CLCD'				:'개인표준직업분류코드(CDD)',
	'INDV_TRN_CPT_DVCD'					:'개인거래자금구분코드',
	'INDV_TRN_CPT_ETC_CNTN'				:'개인거래자금기타내용',
	'INFO_COLT_AGR_NT_AGR_DVCD'			:'정보수집동의미동의구분코드',
	'INFO_DSTC_VAL'						:'당타행납부자구분값',
	'INFO_OFR_AGR_NT_AGR_DVCD'			:'정보제공동의미동의구분코드',
	'INPT_ADDR'							:'입력주소',
	'INPT_DVCD'							:'입력구분',
	'INPT_DVCD_2'						:'입력구분',
	'INQ_CCNT'							:'조회건수',
	'INQ_DVCD'							:'조회구분코드',
	'INQ_EDDT'							:'조회종료일자',
	'INQ_KIND'							:'조회종류',
	'INQ_KND'							:'구분코드',
	'INQ_KND_2'							:'조회구분',
	'INQ_LST_DT'						:'조회마지막일자',
	'INQ_REQT_INSTCD'					:'조회요청기관코드',
	'INQ_STDT'							:'조회시작일자',
	'INQ_STRN_DT'						:'조회시작일자',
	'INRT_N8'							:'이율',
	'INSM_CYCL_DVCD'					:'적립주기구분코드',
	'INSV_ACNO_PWD_C700'				:'적금계좌비밀번호',
	'INSV_NECT_CNPD_DVCD'				:'적금비대면계약기간구분코드',
	'INTS_MNRC_ACNO_C20'				:'이자입금계좌번호',
	'INTS_MNRC_BANK'					:'이자입금은행',
	'INTS_PRVS'							:'이자지급',
	'INTX'								:'소득세',
	'IOMN_DVCD'							:'입출금구분코드',
	'IRCL_PROP_RSCD'					:'금리인하신청사유코드',
	'ISS_DTM'							:'발급일시',
	'ISS_FIN_INSTCD'					:'발급금융기관코드',
	'JBTT_NM'							:'직위명',
	'JEX_BANKCODE'						:'은행코드',
	'JOBKIND'							:'거래유형',
	'KND'								:'구분',
	'KTB_AGENT'							:'KTB_AGENT',
	'KTB_UUID'							:'KTB_UUID',
	'LAMT'								:'대출금액',
	'LAT'								:'지각',
	'LCKN_RESP_VAL'						:'잠김응답값',
	'LISTLEN'							:'LISTLEN',
	'LNP_BASE'							:'조회방식',
	'LOAN_ACNO'							:'대출계좌번호',
	'LOAN_BZWR_DVCD_5'					:'대출업무구분',
	'LOAN_DOC_CNFR_OR_AGR_YN'			:'대출서류확인및동의여부',
	'LOAN_DOC_STRG_OR_KEEP_AGR_YN'		:'대출서류저장및보관동의여부',
	'LOAN_INRT_C9'						:'대출이율',
	'LOAN_PDCD'							:'대출상품코드',
	'LOAN_PROP_AMT'						:'대출신청금액',
	'LOAN_PROP_OPNG_DT'					:'대출신청개시일자',
	'LOAN_RMTN_BANK_ACNO'				:'대출송금은행계좌번호',
	'LOAN_RMTN_BKCD'					:'대출송금은행코드',
	'LOAN_TERM_DT'						:'대출신청기간',
	'LOGIN'								:'사용자ID',
	'LON'								:'LON',
	'LOS_AREA_ADDR'						:'분실지역주소',
	'LOS_DT'							:'분실일자',
	'LST_ATHN_ERR_DTM'					:'마지막인증오류일시',
	'LST_ERR_OCRN_INSTCD'				:'마지막오류발생기관코드',
	'LTC_ALNC_PDCD'						:'롯데카드제휴상품코드',
	'LTERM_N4'							:'대출기간',
	'LTERM_N5'							:'대출기간',
	'LVTP_MNBD_DVCD'					:'생계형주체구분코드',
	'LY_YN'								:'말일여부',
	'MBL_OTP_SRNO_VAL'					:'모바일OTP일련번호값',
	'MESG'								:'메세지',
	'MESG_CLSC_CD'						:'전문종별코드',
	'MESG_DSTC'							:'전문요청구분',
	'MESG_DVCD'							:'전문구분코드',
	'MESG_LEN'							:'전문길이',
	'MGR_NO'							:'관리자번호',
	'MN_BTWN_LMIT_AMT'					:'월간한도(만원단위)',
	'MN_PI_AMT_N15'						:'월납입금액',
	'MN_PRVS_INTS'						:'월지급이자17',
	'MN_PRVS_INTS2'						:'월지급이자2',
	'MN_PYMN_AMT'						:'월불입금액',
	'MNDP_KIND'							:'예금종류',
	'MNRC_ACCO'							:'입금계좌',
	'MNRC_ACCO_16'						:'입금계좌번호16자리',
	'MNRC_ACNO'							:'입금계좌번호',
	'MNRC_ACNO_16'						:'입금계좌번호16자리',
	'MNRC_AMT'							:'입금금액',
	'MNRC_AMT_14'						:'입금금액14자리',
	'MNRC_BANK'							:'입금은행',
	'MNRC_BANK_ACNO'					:'입금은행계좌번호',
	'MNRC_BKCD'							:'입금은행코드',
	'MNRC_BNKB_MRK'						:'통장인자내용',
	'MNRC_WB_ACNO'						:'입금전행계좌번호(납부자끝)',
	'MSG'								:'서명원문',
	'MY_ACCO_DVCD'						:'내계좌구분코드',
	'NEA_TAX_N18'						:'농특세',
	'NECT_ATHN_ACNO'					:'비대면인증계좌번호',
	'NECT_ATHN_BKCD'					:'비대면인증은행코드',
	'NECT_ATHN_STR'						:'인증문자열',
	'NECT_ATHN_TRGT_YN'					:'비대면인증대상고객여부',
	'NECT_ATTR_REG_YN'					:'비대면자동이체등록여부',
	'NECT_BC_SMS_PROP_DVCD'				:'비대면비씨카드SMS신청구분코드',
	'NECT_CHCR_ISS_YN'					:'체크카드신규여부',
	'NECT_CMMD_ACCO_PWD'				:'비대면보통예금계좌비밀번호',
	'NECT_CMMD_ACNO'					:'비대면보통예금계좌번호',
	'NECT_CMMD_MNRC_AMT'				:'비대면보통예금입금금액',
	'NECT_CMMD_NEW_DVCD'				:'비대면보통예금신규구분코드',
	'NECT_CMMD_PDCD'					:'비대면보통예금상품코드',
	'NECT_CMMD_USE_YN'					:'비대면보통예금사용여부',
	'NECT_CMPL_YN'						:'인증완료여부',
	'NECT_CMS_ACNO'						:'비대면CMS계좌번호',
	'NECT_CMS_BKCD'						:'비대면CMS은행코드',
	'NECT_CMS_REG_YN'					:'비대면CMS등록여부',
	'NECT_CUST_REG_CAN_YN'				:'비대면고객등록취소여부',
	'NECT_IDC_KIND_DVCD'				:'비대면신분증종류구분코드',
	'NECT_INBN_REG_YN'					:'전자금융신규여부',
	'NECT_INSV_ACCO_PWD'				:'비대면적금계좌비밀번호',
	'NECT_INSV_CNPD_DCNT'				:'비대면적금계약기간일수',
	'NECT_INSV_CNPD_MMCO'				:'비대면적금계약기간월수',
	'NECT_INSV_CNTR_AMT'				:'비대면적금계약금액',
	'NECT_INSV_MN_PYMN_AMT'				:'비대면적금월불입금액',
	'NECT_INSV_MNRC_AMT'				:'비대면적금입금금액',
	'NECT_INSV_NEW_YN'					:'비대면적금신규여부',
	'NECT_INSV_PDCD'					:'비대면적금상품코드',
	'NECT_INSV_TXTN_DVCD'				:'비대면적금과세구분코드',
	'NECT_INTG_PDCD'					:'비대면통합상품코드',
	'NECT_OWON_ATHN_YN'					:'비대면1원이체인증사용여부',
	'NECT_PIN_NO'						:'비대면PIN번호',
	'NECT_PROD_DTLS_KNCD'				:'비대면상품세부종류코드',
	'NECT_PROD_KNCD'					:'비대면상품종류코드',
	'NECT_TLCL_ATHN_YN'					:'비대면영상통화인증사용여부',
	'NECT_TMDP_ACCO_PWD'				:'비대면정기예금계좌비밀번호',
	'NECT_TMDP_CNPD_DCNT'				:'비대면정기예금계약기간일수',
	'NECT_TMDP_CNPD_MMCO'				:'비대면정기예금계약기간월수',
	'NECT_TMDP_EXPT_DT'					:'비대면정기예금만기일자',
	'NECT_TMDP_MNRC_AMT'				:'비대면정기예금입금금액',
	'NECT_TMDP_NEW_YN'					:'비대면정기예금신규여부',
	'NECT_TMDP_PDCD'					:'비대면정기예금상품코드',
	'NECT_TMDP_SINT_CMIN_DVCD'			:'비대면정기예금단리복리구분코드',
	'NECT_TMDP_TXTN_DVCD'				:'비대면정기예금과세구분코드',
	'NECT_TRN_DD1_LMIT_AMT'				:'1일한도(만원단위)',
	'NECT_TRN_ELEC_CNTR_DVCD'			:'비대면거래전자계약구분코드',
	'NECT_TRN_NO'						:'비대면거래번호',
	'NECT_TRN_TI1_LMIT_AMT'				:'1회한도(만원단위)',
	'NECT_WRCN'							:'비대면동의서건수',
	'NECT_WRCN_CCNT'					:'비대면동의서건수',
	'NEW_ACCO_PWD'						:'신규계좌비밀번호',
	'NEW_DT'							:'신규일자',
	'NEW_USR_PWD'						:'새로운비밀번호',
	'NEXT_DATA_REQT_KEY_VAL'			:'다음데이터요청키값',
	'NO2_ITEM_YN'						:'2번항목여부',
	'NRBR_NO'							:'주민사업자번호',
	'NRBRNO_INQ'						:'주민번호',
	'NRID'								:'주민등록번호',
	'NRIDBRNO_13'						:'주민(사업자)번호',
	'NROM_INTS'							:'정상이자',
	'NT_BILN_INTS_SMAT_18'				:'미징구이자합계',
	'NT_BILN_PRNC_BLNK_18'				:'미징구원금잔액',
	'NTS_SCRG_DTA_PPCD'					:'국세청스크래핑자료용도코드',
	'NTS_SCRG_DTA_PRPL_DVCD'			:'국세청스크래핑자료제출처구분코드',
	'OFCL_ELEC_DOCU_ARCH_STCD'			:'공전소상태',
	'OOBK_DVCD'							:'기존OTP당/타행구분',
	'OPIN_NO'							:'PIN번호',
	'ORD_TYPE'							:'신청구분',
	'OTIN_ACDT_RCVR_YN'					:'타기관사고회복여부',
	'OTIN_ATMT_REG_OTP_SRNO'			:'타기관자동등록OTP일련번호',
	'OTIN_ATMT_REG_TRGT_CO_CD'			:'타기관자동등록대상업체코드',
	'OTP_LEN'							:'OTP길이',
	'OTP_OTPT_VAL1'						:'OTP출력값1',
	'OTP_OTPT_VAL2'						:'OTP출력값2',
	'OTP_SRNO_VAL'						:'OTP일련번호값',
	'OTP_SRNO1'							:'폐기/해지OTP일련번호',
	'OTP_SRNO2'							:'신규OTP일련번호',
	'OTP_STCD'							:'OTP상태코드',
	'OTP_VNDR_CD'						:'OTP벤더코드',
	'OTP_VNDR_CD1'						:'폐기/해지OTP벤더코드',
	'OTP_VNDR_CD2'						:'신규OTP벤더코드',
	'OTU_ATHN_NO'						:'일회용인증번호',
	'OUT_REC'							:'OUT_REC',
	'OUTL'								:'적요',
	'OVFE'								:'연체료',
	'OVRD_INTS'							:'연체이자',
	'PADD'								:'응당일',
	'PARE_KNCD'							:'요금종류',
	'PAYM_HOPE_DD'						:'이체희망일',
	'PAYR_AMT_15'						:'이체금액',
	'PAYR_MNRC_ACNO'					:'입금계좌번호',
	'PAYR_MNRC_BKCD'					:'입금은행코드',
	'PAYR_NO'							:'납부자번호',
	'PAYR_OPEN_BO_CD'					:'납부자개설점코드',
	'PAYR_TLNO'							:'납부자전화번호',
	'PAYR_TRNF_EPRT_DT'					:'마감월',
	'PAYR_TRNF_OPNG_DT'					:'납부자이체개시일자',
	'PDCD'								:'상품코드',
	'PI_RND_5'							:'납입회차',
	'PIN_RESP'							:'PIN응답',
	'PRE_CNT'							:'기신청건수',
	'PRE_EXIS_DMNB_ACCO_1'				:'기존재요구불계좌1',
	'PRE_EXIS_DMNB_ACCO_2'				:'기존재요구불계좌2',
	'PRE_EXIS_DMNB_ACCO_3'				:'기존재요구불계좌3',
	'PRE_EXIS_DMNB_ACCO_CCNT'			:'기존재요구불계좌건수',
	'PRE_NECT_PROD_DTLS_KNCD'			:'기신청비대면상품세부종류코드',
	'PRE_NECT_TRN_NO'					:'기신청비대면거래번호',
	'PROC_FLAG'							:'처리구분',
	'PROCS_KND'							:'처리구분',
	'PROD_GDNC_MTH_FUR_XN'				:'상품서비스안내수단DM',
	'PROD_GDNC_MTH_ONE_XN'				:'상품서비스안내수단문자메세지',
	'PROD_GDNC_MTH_THR_XN'				:'상품서비스안내수단전화',
	'PROD_GDNC_MTH_TWO_XN'				:'상품서비스안내수단이메일',
	'PROD_KIND'							:'상품종류',
	'PROD_KIND_C2'						:'상품종류',
	'PROD_NM'							:'상품명',
	'PROD_SCV_DM_YN'					:'상품서비스안내수단DM',
	'PROD_SCV_EML_YN'					:'상품서비스안내수단이메일',
	'PROD_SCV_LTRS_YN'					:'상품서비스안내수단문자메세지',
	'PROD_SCV_TEL_YN'					:'상품서비스안내수단전화',
	'PROD_SVC_COLT_UZ_AGR_DVCD'			:'상품서비스수집이용동의구분코드',
	'PROD_SVC_INFO_OFR_AGR_DVCD'		:'상품서비스정보제공동의구분코드',
	'PROP_CARD_DVCD'					:'신청카드구분코드',
	'PROP_DSTC'							:'신청구분(타행)',
	'PROP_DSTC_2'						:'신청구분',
	'PROP_DT'							:'신청일자',
	'PROP_EDDT'							:'신청일자(TO)',
	'PROP_LAMT_N17'						:'대출금액',
	'PROP_RPY_TERM_MMCO'				:'신청상환기간월수(응당일)',
	'PRTB_TFNO'							:'휴대전화국번호',
	'PRTB_TSNO'							:'휴대전화서비스번호',
	'PRTB_TVNO'							:'휴대전화개별번호',
	'PRVS_INTS'							:'지급이자',
	'PRVS_INTS2'						:'지급이자2',
	'PSNT_PSWD'							:'현재비밀번호',
	'PSNT_RSDC_ADDR'					:'현재거주지주소',
	'PSNT_RSDC_BLDG_MNGNO'				:'현재거주지건물관리번호',
	'PSNT_RSDC_BSIC_ADDR'				:'현재거주지기본주소',
	'PSNT_RSDC_DTAD'					:'현재거주지상세주소',
	'PSNT_RSDC_REF_ITEM_NM'				:'현재거주지참조항목명',
	'PSNT_RSDC_REFAD'					:'현재거주지참조항목명',
	'PSNT_RSDC_ZPCD'					:'현재거주지우편번호',
	'PSWD_700'							:'비밀번호',
	'PWD'								:'비밀번호',
	'PWD_16'							:'비밀번호',
	'PYMN_AMT_N15'						:'불입금액',
	'QLFC_GNLS_CMP_NCNT'				:'자격득실회사갯수',
	'RCK_DT'							:'기산일자',
	'REC'								:'REC',
	'REC_CNT_5'							:'자료건수',
	'RECV'								:'받으시는분',
	'REG_CD'							:'등록코드',
	'REG_DATE'							:'등록일',
	'REG_DVCD'							:'등록구분',
	'REG_ID'							:'등록자아이디',
	'REG_ISS_DT_C8'						:'주민등록증발급일자',
	'REG_TIME'							:'등록시간',
	'REG_TRMT_DSTC1'					:'등록해지구분',
	'REG_TRN_NO'						:'등록거래번호',
	'REGS_DT'							:'등재일자',
	'REGS_TKTM'							:'등재시간',
	'REMN_DCNT_PRVS_INTS'				:'잔여일수지급이자',
	'REMN_DCNT_PRVS_INTS2'				:'잔여일수지급이자2',
	'REQT_BO'							:'요청지점',
	'REQT_STRN_LOC'						:'요청시작위치',
	'RESP_CD'							:'응답코드',
	'RFM_LNBR_ZPCD_SRNO'				:'정제지번우편번호일련번호',
	'RL_OWNR_YN'						:'실제소유자여부',
	'RLNM_ATHN_DSTC_C2'					:'실명인증표구분',
	'RLT_NM'							:'관계명',
	'RLTR_YN'							:'실거래유무',
	'RMTN_RQPS2'						:'송금의뢰인',
	'RNNO'								:'실명번호',
	'RNNO_C13'							:'실명번호',
	'RNNORNNO'							:'주민등록번호',
	'RPMT_INTS'							:'환출이자',
	'RPR_NM'							:'대표자명',
	'RPY_AMT'							:'상환금액',
	'RPY_FEE'							:'상환수수료',
	'RPY_RND'							:'상환회차',
	'RRNO'								:'주민사업자번호',
	'RRT_ADDR_CHG_CNT'					:'등본주소변동개수',
	'RRT_ADDR_HSTR_IFMY_CNT'			:'등본주소이력약식개수',
	'RRT_DOCU_CNFR_NO'					:'등본문서확인번호',
	'RRT_GNRT_CSTN_CNT'					:'등본세대구성원개수',
	'RRT_HHLD_CMPS_DT'					:'등본세대주구성일자',
	'RRT_HHLD_CMPS_RSN'					:'등본세대주구성사유',
	'RRT_HHLD_NM'						:'등본세대주이름',
	'RRT_PROP_DT'						:'등본신청일',
	'RRT_PROP_PS_BRDD'					:'등본신청인생년월일',
	'RRT_PROP_PS_NM'					:'등본신청인이름',
	'RSTX'								:'주민세',
	'RVCT_DT'							:'해제일자',
	'RVCT_TM'							:'해제시각',
	'RVN_ALTX'							:'수입제세',
	'RVN_ALTX2'							:'수입제세2',
	'SAVINGBANK_CODE'					:'저축은행코드',
	'SBCD'								:'저축은행코드',
	'SBTR_MN_INTS'						:'차감지급월이자',
	'SBTR_MN_INTS2'						:'차감지급월이자2',
	'SBTR_PRVS_AMT'						:'차감지급금액',
	'SBTR_PRVS_AMT_N18'					:'차감지급액',
	'SBTR_PRVS_AMT2'					:'차감지급금액2',
	'SBTR_REMN_DCNT_INTS'				:'차감지급잔여일수이자',
	'SBTR_REMN_DCNT_INTS2'				:'차감지급잔여일수이자2',
	'SBTR_TOT_INTS'						:'차감지급총이자',
	'SBTR_TOT_INTS2'					:'차감지급총이자2',
	'SCNT'								:'매수',
	'SCRG_ANL_INCM_AMT'					:'스크래핑년간소득금액',
	'SCRG_APL_YN'						:'스크래핑적용여부',
	'SCSS_YN'							:'탈퇴여부',
	'SECU_CARD_INDC_NO1'				:'보안카드지시번호#1',
	'SECU_CARD_INDC_NO2'				:'보안카드지시번호#2',
	'SECU_CARD_PWD1_700'				:'보안카드비밀번호1',
	'SECU_CARD_PWD2_700'				:'보안카드비밀번호2',
	'SECU_CARD_SRNO'					:'보안카드일련번호',
	'SECU_MEDI'							:'보안매체',
	'SECU_MEDI_DVCD'					:'보안매체구분코드',
	'SELF_YN'							:'본인여부',
	'SESSIONID'							:'세션ID',
	'SETP_AMT'							:'설정금액',
	'SGI_INSU_INCM_AMT_DVCD'			:'서울보증보험소득금액구분코드',
	'SGI_INSU_LOAN_DVCD'				:'서울보증보험대출구분코드',
	'SGI_INSU_SLE_CHNL_DVCD'			:'서울보증보험판매채널구분코드',
	'SGI_INSU_STDL_PROD_DVCD'			:'서울보증보험사잇돌상품구분코드',
	'SGNR_CMPL_DDTM'					:'인증서서명일자',
	'SGSR'								:'권유자',
	'SGSR_NO'							:'권유자번호',
	'SGST_USRNO'						:'권유사용자번호',
	'SID_ACNO'							:'예적금계좌번호',
	'SID_MORT_ACNO'						:'예적금담보계좌번호',
	'SID_PWD_C700'						:'예적금비밀번호',
	'SIG'								:'서명',
	'SIGN_DATA'							:'전자서명정보',
	'SINT_CMIN_DVCD'					:'단리복리구분코드',
	'SM_ATM_WTCH_ACNO'					:'스마트출금등록계좌번호',
	'SMDD'								:'결제일',
	'SMS_RCMS_YN'						:'SMS수신여부',
	'SMS_YN'							:'문자메세제수신동의여부',
	'SMT_BNK_YN'						:'스마트뱅킹여부',
	'SNLN_CMCM_DVCD'					:'햇살론통신사구분코드',
	'SNLN_DWAR_OWN_DVCD'				:'햇살론주거지소유구분코드',
	'SNLN_EMLM_DVCD'					:'햇살론고용구분코드',
	'SNLN_INRT_CHG_CYCL_CD'				:'햇살론금리변동주기코드',
	'SNLN_LTERM_CD'						:'햇살론대출기간코드',
	'SPEL_INRT'							:'특별이율',
	'SPEL_INRT2'						:'특별이율2',
	'SPEL_INTS'							:'특별이자',
	'SPEL_INTS2'						:'특별이자2',
	'SRNO'								:'일련번호',
	'STAT'								:'처리구분',
	'STCD'								:'상태구분',
	'STDT'								:'시작일자',
	'STRG_FILE_PATH_NM'					:'저장파일경로명',
	'STRN'								:'시작',
	'STS_DVCD'							:'상품구분코드',
	'SVBN_ACNO'							:'저축은행계좌번호',
	'SVBN_BOCD'							:'저축은행지점코드',
	'SVBN_GVCR_TRN_STPL_AGR_YN'			:'저축은행여신거래약관동의여부',
	'SVNG_KIND'							:'저축종류',
	'TEL_YN'							:'전화수신동의여부',
	'TI1_TRNF_LMIT'						:'1회이체한도',
	'TI1_TRNF_LMIT_AMT'					:'1회이체한도금액',
	'TMDP_NECT_CNPD_DVCD'				:'정기예금비대면계약기간구분코드',
	'TMDP_PWD_C700'						:'정기예금비밀번호',
	'TNRC_DSTC'							:'송수신구분',
	'TOKEN'								:'토큰',
	'TOT_AST_AMT_DVCD'					:'총자산금액구분코드',
	'TOT_INSM_AMT'						:'총적립금액',
	'TOT_INSM_AMT2'						:'총적립금액2',
	'TOT_INTS'							:'총이자',
	'TOT_INTS2'							:'총이자2',
	'TOT_RVN_ALTX'						:'총수입제세',
	'TOT_RVN_ALTX2'						:'총수입제세2',
	'TRGB'								:'거래구분',
	'TRL_DSTC'							:'시도구분코드',
	'TRL_NM'							:'시도명',
	'TRMN_IPAD'							:'단말IP주소',
	'TRMN_TRN_DVCD'						:'단말거래구분코드',
	'TRMT_AMT_N15'						:'해지원금',
	'TRMT_AMT_N17'						:'해지금액',
	'TRMT_AMT_N18'						:'해지원금',
	'TRMT_CD'							:'해지코드',
	'TRMT_DT'							:'해지일자',
	'TRMT_INTS'							:'해지이자',
	'TRN_DSTC'							:'거래구분',
	'TRN_DSTC_2'						:'거래구분',
	'TRN_DSTC_4'						:'거래구분',
	'TRN_DT_FROM'						:'조회시작일',
	'TRN_DT_TO'							:'조회종료일',
	'TRN_DVCD'							:'거래구분',
	'TRN_INFO'							:'거래정보',
	'TRN_INFO_HASH_VAL'					:'거래정보해쉬값',
	'TRN_INFO_LEN'						:'거래정보길이',
	'TRN_INFO_YN'						:'거래정보유무',
	'TRN_KNCD'							:'거래종류',
	'TRN_SRNO_10'						:'거래일련번호',
	'TRN_SRNO_28'						:'일련번호',
	'TRNF_AMT'							:'이체금액',
	'TRNF_AMT_13'						:'이체금액',
	'TRNF_CCNT'							:'이체건수(납부자시작)',
	'TRNF_END_YM'						:'이체종료년월',
	'TRNF_HOPE_DD_DVCD'					:'이체희망일구분코드',
	'TRNF_SCS_YN'						:'이체성공여부',
	'TRNF_STRN_YM'						:'이체시작년월',
	'TRTM_DVCD'							:'처리구분',
	'TX_KND'							:'업무구분',
	'TX_KND_N1'							:'업무구분',
	'TXTN_CD'							:'과세코드',
	'TXTN_DVCD'							:'과세구분코드',
	'TYPE'								:'타입',
	'UNQ_IDNT_INFO_AGR_YN'				:'고유식별정보처리동의여부',
	'USE_DVCD'							:'사용구분',
	'USER_ID'							:'이용자ID',
	'USER_ID_12'						:'사용자ID',
	'USER_IDNT_CD'						:'사용자식별코드',
	'USER_SSN'							:'저축은행코드',
	'USERID'							:'사용자ID',
	'USG_DVCD'							:'용도구분',
	'USR_ID'							:'이용자ID',
	'USR_ID_12'							:'이용자ID',
	'UUID'								:'범용고유식별자',
	'UUSE_AMT'							:'저축종류별미사용금액',
	'UZ_REG_DTM'						:'이용등록일시',
	'UZ_REG_INSTCD'						:'이용등록기관코드',
	'UZ_REG_YN'							:'이용등록여부',
	'UZ_SGST_EML_AGR_NT_AGR_DVCD'		:'이용권유이메일동의미동의구분코드',
	'UZ_SGST_INWT_AGR_NT_AGR_DVCD'		:'이용권유서면동의미동의구분코드',
	'UZ_SGST_SMS_AGR_NT_AGR_DVCD'		:'이용권유SMS동의미동의구분코드',
	'UZ_SGST_TEL_AGR_NT_AGR_DVCD'		:'이용권유전화동의미동의구분코드',
	'VLD_DLN_YM'						:'유효기한년월',
	'WB_ACNO'							:'전행계좌번호',
	'WHL_CNT'							:'전체건수',
	'WORK_DEPT_NM'						:'근무부서명',
	'WORK_KIND'							:'직업구분',
	'WRST_ADDR'							:'직장주소',
	'WRST_ADDR_REF_ITEM_NM'				:'직장참고주소',
	'WRST_BLDG_MNGNO'					:'직장건물관리번호',
	'WRST_BSIC_ADDR'					:'직장기본주소',
	'WRST_DTAD'							:'직장상세주소',
	'WRST_NM'							:'직장명',
	'WRST_REF_ITEM_NM'					:'직장참조항목명',
	'WRST_REFAD'						:'직장참조주소',
	'WRST_TLNO'							:'직장전화번호',
	'WRST_TLNO1'						:'근무처전화1',
	'WRST_TLNO2'						:'근무처전화2',
	'WRST_TLNO3'						:'근무처전화3',
	'WRST_ZPCD'							:'직장우편번호',
	'WRST_ZPCD_ADDR'					:'직장우편번호주소',
	'WTCH_ACCO_C20'						:'출금계좌',
	'WTCH_ACCO_C700'					:'출금계좌비밀번호',
	'WTCH_ACCO_REG_YN'					:'출금계좌등록여부',
	'WTCH_ACNO'							:'출금계좌번호',
	'WTCH_ACNO_16'						:'출금계좌번호16자리',
	'WTCH_ACNO_20'						:'출금계좌번호20자리(납부자)',
	'WTCH_ACNO_C20'						:'출금계좌번호',
	'WTCH_AMT'							:'출금금액',
	'WTCH_BANK_ACNO'					:'출금은행계좌번호',
	'WTCH_BKCD'							:'출금은행코드',
	'WTCH_BNKB_MRK'						:'출금통장표시',
	'YR_BIZ_INCM_AMT'					:'연사업소득금액',
	'YR_LBR_INCM_AMT'					:'연근로소득금액',
	'YR_PNSN_INCM_AMT'					:'연연금소득금액',
	'ZPCD'								:'우편번호',
	'ZPCD_ADDR'							:'우편번호주소',
	'ZPCD_MNGNO'						:'우편번호관리번호',
	'ZPSR_C3'							:'우편일련번호',
	'USR_PWD'							:'사용자비밀번호',
	'API_RS_MSG'						:'API결과메세지',
	'LAST_CNCT_TKTM'					:'최종접속시간',
	'INDV_BUSI_DVCD'					:'개인사업자여부',
	'LAST_CNCT_DT'						:'최종접속일자',
	'USER_NM'							:'사용자명',
	'REXC_YN'							:'재수행여부',
	'HOME_TLNO'							:'집전화번호',
	'OTP_GE_DATE'						:'OTP보증만료기간',
	'DTA_NCNT'							:'자료건수',
	'STPL_PASS_YN'						:'약관 확인 결과 통과 여부',
	'SMPH_ADDT_ATHN_KNCD'				:'스마트폰추가인증종류코드',
	'TEL_ADDT_ATHN_KNCD'				:'전화추가인증종류코드',
	'SMS_ADDT_ATHN_KNCD'				:'SMS추가인증종류코드',
	'COM_TLNO'							:'직장전화번호',
	'PCOM_ADDT_ATHN_KNCD'				:'PC추가인증종류코드',
	'OTP_GS_DATE'						:'OTP보증시작기간',
	'SIGN_DVCD'							:'부호구분코드',
	'ACNT_BLNC'							:'계좌잔액',
	'BNKB_WTCH_POSB_YN'					:'통장출금가능여부',
	'ACCO_STS_NM'						:'계좌상태명',
	'ACCO_STS_CD'						:'계좌상태코드',
	'ACCO_NICK'							:'계좌별명',
	'CMPH_BNKB_YN'						:'종합통장설정여부',
	'SCHD_APL_INRT'						:'예정적용이율',
	'NECT_IDC_REG_YN'					:'비대면신분증등록여부',
	'APRV_AMT'							:'승인금액',
	'CHRG_EMP_NM'						:'담당직원명',
	'NECT_PROD_NM'						:'비대면상품명',
	'NECT_LOAN_RPY_MTHD'				:'비대면대출상환방식',
	'LOAN_SCHD_EXPT_DT'					:'대출예정만기일자',
	'GRNY_LMIT_AMT'						:'보증한도금액',
	'CHGR_PRTB_TFNO'					:'담당자휴대전화국번호',
	'NECT_INTR_AMTH_CD'					:'비대면금리적용방식코드',
	'CHGR_PRTB_TSNO'					:'담당자휴대전화서비스번호',
	'CHGR_PRTB_TVNO'					:'담당자휴대전화개별번호',
	'NECT_EXTR_INST_TRN_STCD'			:'비대면외부기관거래상태코드',
	'AFTR_BLNC_18'						:'거래후잔액',
	'AMT'								:'금액',
	'BLNC_SIGN'							:'잔액부호',
	'CLOT_COUNT'						:'호출카운트',
	'FEE'								:'수수료',
	'FEE1'								:'수수료',
	'LDGR_STCD'							:'원장상태코드',
	'MNRC_AMT2'							:'입금금액',
	'MNRC_NM'							:'수취인',
	'PRCS_KEY'							:'이체프로세스키',
	'PSNT_TM'							:'현재시각',
	'RECV_NM'							:'수취인명',
	'RECV1'								:'수취인',
	'RMTN_ACTNO'						:'송금계좌번호',
	'RMTN_REG_GUID'						:'송금등록GUID',
	'RQPS'								:'의뢰인',
	'RSPN_CD'							:'응답코드',
	'TRN_AMOUNT'						:'간편이체가능금액',
	'TRN_BNK_CD'						:'저축은행코드',
	'TRN_DATE'							:'업데이트시간',
	'TRN_DAY'							:'간편이체일',
	'TRN_UNNO'							:'거래고유번호',
	'TRN_USER_ID'						:'사용자_ID',
	'TRNF_AF_BLNC'						:'이체후잔액',
	'TRNF_STS'							:'이체상태',
	'VLD_EDDTM'							:'유효종료일시',
	'WTCH_ACCO'							:'출금계좌',
	'WTCH_ACCO_BLNC'					:'출금계좌잔액',
	'WTCH_ACNO2'						:'출금계좌번호',
	'WTCH_POSB_BLNC'					:'출금가능잔액',
	'LOAN_PRNC'              : '대출원금',
	'ACCO_STCD'              : '계좌상태코드',
	'LOAN_BLNC'              : '대출잔액',
	'DBTR_NM'                : '채무자명',
	'LOAN_DT'                : '대출일자',
	'LOAN_EPRT_DT'           : '대출만료일자',
	'PADD'                   : '응당일',
	'LAST_ITRV_DT'           : '최종이수일자',
	'NXTR_INTS_PI_DT'        : '차기이자납입일',
	'NROM_INRT'              : '정상이율',
	'OVRD_INRT'              : '연체이율(시작)',
	'OVRD_INRT_2'            : '연체이율2(종료)',
	'LAST_TRN_DT'            : '최종거래일',
	'NEXT_TRAN_YN'           : '다음거래유무',
	'DTA_NCNT'               : '자료건수',
	'NEXT_DATA_XN'           : '다음데이터유무',
	'TI1_LMIT'               : '1회 한도',
	'DD1_LMIT'               : '1일 한도',
	'SECU_MEDI_TI1_LMIT'     : '보안매체 1회한도',
	'SECU_MEDI_DD1_LMIT'     : '보안매체 1일한도',
	'REAL_TI1_LMIT'          : '실제 1회한도',
	'REAL_DD1_LMIT'          : '실제 1일한도',
	'TDD_TRNF_AMT'           : '당일이체금액',
	'TI1_REMN_TRNF_LMIT'     : '1회잔여이체한도',
	'DD1_REMN_TRNF_LMIT'     : '1일잔여이체한도',
	'CMBB_SETP_AMT'          : '종통설정금액',
	'PSNT_BLNC_SIGN'         : '현재잔액부호',
	'PSNT_BLNC'              : '현재잔액',
	'TOT_OTBR'               : '총타점',
	'INQ_MNDR_OTBR'          : '조회필타점',
	'PRVS_POSB_AMT'          : '지급가능금액',
	'TI1_TRNF_POSB_AMT'      : '1회이체가능금액',
	'DD1_TRNF_POSB_AMT'      : '1일이체가능금액',
	'IN_LIMT_FLG'            : '입금지정서비스사용여부',
	'UN_DAY_LIMT'            : '미지정입금 1일이체한도',
	'UN_ONE_LIMT'            : '미지정입금 1일누적금액',
	'TRMT_CD'                : '해지코드',
	'TRMT_DT'                : '해지일자',
	'TRMT_AMT_N15'           : '해지원금',
	'EXPT_DT'                : '만기일자',
	'EXPT_CAOV_DT'           : '만기이연일자',
	'TRMT_INTS_N15'          : '해지이자',
	'INTX_N15'               : '소득세',
	'RSTX_N15'               : '주민세',
	'NEA_TAX_N15'            : '농특세',
	'IMPR_ALTX_SUM_N15'      : '수입제세합계',
	'RETN_INTS_N15'          : '환입이자',
	'RPMT_IMPR_ALTX_N15'     : '환출수입제세',
	'SBTR_PRVS_AMT_N15'      : '차감지급액',
	'TRMT_DTL_CD'            : '해지상세코드',
	'INRT_CHNG_CNT'          : '이율변경건수',
	'TMNL_ID'                : '단말기 ID',
	'TMNL_NNM'               : '단말기닉네임',
	'PC_DSGT_APL_TRGT'       : 'PC지정 적용대상 업무',
	'TMNL_TYPE'              : '단말기 장치타입',
	'REG_DT'                 : '등록일자',
	'API_RS_MSG'             : 'API 결과 메시지'

};